# Project: TSO_test
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = TSO_test.o ../basic/alglib/alglibinternal.o ../basic/alglib/alglibmisc.o ../basic/alglib/ap.o ../basic/alglib/kernels_fma.o ../basic/alglib/linalg.o ../basic/alglib/optimization.o ../basic/alglib/solvers.o ../power_market/power_market_func.o ../power_network/power_network_input.o ../basic/alglib/kernels_avx2.o
LINKOBJ  = TSO_test.o ../basic/alglib/alglibinternal.o ../basic/alglib/alglibmisc.o ../basic/alglib/ap.o ../basic/alglib/kernels_fma.o ../basic/alglib/linalg.o ../basic/alglib/optimization.o ../basic/alglib/solvers.o ../power_market/power_market_func.o ../power_network/power_network_input.o ../basic/alglib/kernels_avx2.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -fopenmp
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"D:/Programs/C++/tools/boost_1_78_0" -I"D:/Programs/C++/tools/eigen-3.4.0"
BIN      = TSO_test.exe
CXXFLAGS = $(CXXINCS) -fopenmp -mavx2 -mfma -DNDEBUG -O3 -s -std=c++2a
CFLAGS   = $(INCS) -fopenmp -mavx2 -mfma -DNDEBUG -O3 -s -std=c++2a
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

TSO_test.o: TSO_test.cpp
	$(CPP) -c TSO_test.cpp -o TSO_test.o $(CXXFLAGS)

../basic/alglib/alglibinternal.o: ../basic/alglib/alglibinternal.cpp
	$(CPP) -c ../basic/alglib/alglibinternal.cpp -o ../basic/alglib/alglibinternal.o $(CXXFLAGS)

../basic/alglib/alglibmisc.o: ../basic/alglib/alglibmisc.cpp
	$(CPP) -c ../basic/alglib/alglibmisc.cpp -o ../basic/alglib/alglibmisc.o $(CXXFLAGS)

../basic/alglib/ap.o: ../basic/alglib/ap.cpp
	$(CPP) -c ../basic/alglib/ap.cpp -o ../basic/alglib/ap.o $(CXXFLAGS)

../basic/alglib/kernels_fma.o: ../basic/alglib/kernels_fma.cpp
	$(CPP) -c ../basic/alglib/kernels_fma.cpp -o ../basic/alglib/kernels_fma.o $(CXXFLAGS)

../basic/alglib/linalg.o: ../basic/alglib/linalg.cpp
	$(CPP) -c ../basic/alglib/linalg.cpp -o ../basic/alglib/linalg.o $(CXXFLAGS)

../basic/alglib/optimization.o: ../basic/alglib/optimization.cpp
	$(CPP) -c ../basic/alglib/optimization.cpp -o ../basic/alglib/optimization.o $(CXXFLAGS)

../basic/alglib/solvers.o: ../basic/alglib/solvers.cpp
	$(CPP) -c ../basic/alglib/solvers.cpp -o ../basic/alglib/solvers.o $(CXXFLAGS)

../power_market/power_market_func.o: ../power_market/power_market_func.cpp
	$(CPP) -c ../power_market/power_market_func.cpp -o ../power_market/power_market_func.o $(CXXFLAGS)

../power_network/power_network_input.o: ../power_network/power_network_input.cpp
	$(CPP) -c ../power_network/power_network_input.cpp -o ../power_network/power_network_input.o $(CXXFLAGS)

../basic/alglib/kernels_avx2.o: ../basic/alglib/kernels_avx2.cpp
	$(CPP) -c ../basic/alglib/kernels_avx2.cpp -o ../basic/alglib/kernels_avx2.o $(CXXFLAGS)
