trEnD: local Namespace Reference
local Namespace Reference
Functions
void aggregators_settlement_print (power_market::market_whole_inform &Power_market_inform)
void BME_copula (spatial_field::estimation_inform &inform, power_network::network_inform &Power_network_inform, Eigen::SparseMatrix< double > &Constraint, double tol)
void BME_linear (spatial_field::estimation_inform &inform, Eigen::SparseMatrix< double > &Constraint)
void cross_border_settlement_print (power_market::market_whole_inform &Power_market_inform)
void end_users_settlement_print (power_market::market_whole_inform &Power_market_inform, power_network::network_inform &Power_network_inform)
void industrial_settlement_print (power_market::market_whole_inform &Power_market_inform)
void Market_results_print (power_market::market_inform &Market, std::string name, configuration::process_config &process_par, bool nodal=1)
Eigen::RowVectorXd output_row_store (int col_num, agent::settlement_struct &settlement)
Eigen::VectorXcd Pade (Eigen::VectorXcd c)
void power_flow_transmission_results_print (power_market::market_inform &Market, std::string name, configuration::process_config &process_par)
void power_flow_whole_results_print (power_network::network_inform &Power_network_inform, std::string name, configuration::process_config &process_par)
void power_supplier_settlement_print (power_market::market_whole_inform &Power_market_inform)
void Simplified_network_print (power_market::market_inform &Market, std::string name)
void Sink_Node_Set (power_market::market_inform &DSO_Market, power_network::DSO_cluster_struct &DSO_cluster)
void Source_Node_Set (power_market::market_inform &DSO_Market, power_network::DSO_cluster_struct &DSO_cluster)
std::vector< std::string > var_names_set ()
Function Documentation
aggregators_settlement_print()
void local::aggregators_settlement_print (power_market::market_whole_inform & Power_market_inform)
Definition at line 74 of file agent_output.cpp.
References power_market::market_whole_inform::agent_profiles, power_market::agent_profiles_struct::aggregators, output_row_store(), var_names_set(), and basic::write_file().
Referenced by agent::agents_results_print().
BME_copula()
void local::BME_copula (spatial_field::estimation_inform & inform, power_network::network_inform & Power_network_inform, Eigen::SparseMatrix< double > & Constraint, double tol)
Definition at line 5 of file spatial_field.cpp.
References spatial_field::estimation_inform::alpha_iteration, power_network::points_struct::covariance, spatial_field::estimation_inform::mu, spatial_field::estimation_inform::mu_mean, spatial_field::estimation_inform::mu_scale, spatial_field::estimation_inform::norm_dist, power_network::network_inform::points, and spatial_field::estimation_inform::x.
Referenced by spatial_field::demand_imbalance_estimation(), spatial_field::solar_radiation_estimation(), and spatial_field::wind_on_cf_estimation().
BME_linear()
void local::BME_linear (spatial_field::estimation_inform & inform, Eigen::SparseMatrix< double > & Constraint)
Definition at line 58 of file spatial_field.cpp.
References spatial_field::estimation_inform::Conversion_Mat_1, spatial_field::estimation_inform::Conversion_Mat_2, spatial_field::estimation_inform::mu, spatial_field::estimation_inform::mu_mean, and spatial_field::estimation_inform::mu_scale.
Referenced by spatial_field::demand_imbalance_estimation().
cross_border_settlement_print()
void local::cross_border_settlement_print (power_market::market_whole_inform & Power_market_inform)
Definition at line 89 of file agent_output.cpp.
References power_market::market_whole_inform::agent_profiles, power_market::agent_profiles_struct::cross_border, output_row_store(), var_names_set(), and basic::write_file().
Referenced by agent::agents_results_print().
end_users_settlement_print()
void local::end_users_settlement_print (power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 116 of file agent_output.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_market::agent_profiles_struct::end_user_type, power_market::agent_profiles_struct::end_users, output_row_store(), power_network::network_inform::points, var_names_set(), and basic::write_file().
Referenced by agent::agents_results_print().
industrial_settlement_print()
void local::industrial_settlement_print (power_market::market_whole_inform & Power_market_inform)
Definition at line 136 of file agent_output.cpp.
References power_market::market_whole_inform::agent_profiles, agent::industrial::profiles::HV, power_market::agent_profiles_struct::industrial, output_row_store(), var_names_set(), and basic::write_file().
Referenced by agent::agents_results_print().
Market_results_print()
void local::Market_results_print (power_market::market_inform & Market, std::string name, configuration::process_config & process_par, bool nodal = 1)
Definition at line 29 of file power_market_output.cpp.
References power_market::market_inform::actual, power_market::network_graph::actual_power, power_market::schedule::balancing, power_market::market_inform::balancing, power_market::market_inform::confirmed, power_market::network_graph::confirmed_power, power_market::settlement::cost, power_market::schedules::cross_border, power_market::results::demand, power_market::settlement::demand_down, power_market::settlement::demand_up, power_market::schedules::end_user, power_market::schedule::EOM, power_market::market_inform::EOM, power_market::schedules::hydro, power_market::market_inform::imbalance, power_market::schedules::industrial, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::market_inform::operation, power_market::results::price, power_market::settlement::price_demand, power_market::settlement::price_down, power_market::settlement::price_supply, power_market::settlement::price_up, power_market::schedules::pump_storage, power_market::schedule::redispatch, power_market::market_inform::redispatch, power_market::schedules::slack, power_market::results::supply, power_market::settlement::supply_down, power_market::settlement::supply_up, configuration::process_config::time_boundary, power_market::settlement::utility, power_market::schedules::wind, basic::write_file(), and power_market::market_inform::zone_names.
Referenced by power_market::Markets_results_print().
output_row_store()
Eigen::RowVectorXd local::output_row_store (int col_num, agent::settlement_struct & settlement)
Definition at line 40 of file agent_output.cpp.
References agent::settlement_process::balancing, agent::settlement_process::BESS, agent::settlement_struct::cost_demand, agent::settlement_struct::cost_supply, agent::settlement_process::EOM, agent::settlement_process::imbalance, agent::settlement_struct::price, agent::settlement_process::redispatch, agent::settlement_struct::reimburse, agent::settlement_struct::utility_demand, agent::settlement_struct::utility_supply, agent::settlement_struct::volume_demand, agent::settlement_struct::volume_demand_down, agent::settlement_struct::volume_demand_up, agent::settlement_struct::volume_supply, agent::settlement_struct::volume_supply_down, and agent::settlement_struct::volume_supply_up.
Referenced by aggregators_settlement_print(), cross_border_settlement_print(), end_users_settlement_print(), industrial_settlement_print(), and power_supplier_settlement_print().
Pade()
Eigen::VectorXcd local::Pade (Eigen::VectorXcd c)
Definition at line 27 of file power_flow_analysis.cpp.
power_flow_transmission_results_print()
void local::power_flow_transmission_results_print (power_market::market_inform & Market, std::string name, configuration::process_config & process_par)
Definition at line 8 of file power_flow_output.cpp.
References power_network::power_flow_struct::current_abs, power_network::power_flow_struct::current_arg, power_network::power_flow_struct::P_node, power_market::market_inform::power_flow, power_network::power_flow_struct::Q_node, configuration::process_config::time_boundary, power_network::power_flow_struct::voltage_abs, power_network::power_flow_struct::voltage_arg, basic::write_file(), and power_market::market_inform::zone_names.
Referenced by power_network::power_flow_results_print().
power_flow_whole_results_print()
void local::power_flow_whole_results_print (power_network::network_inform & Power_network_inform, std::string name, configuration::process_config & process_par)
Definition at line 35 of file power_flow_output.cpp.
References power_network::points_struct::bidding_zone, power_network::nodes_struct::bidding_zone, power_network::network_inform::nodes, power_network::network_inform::points, power_network::network_inform::power_flow, configuration::process_config::time_boundary, power_network::power_flow_struct::voltage_abs, power_network::power_flow_struct::voltage_arg, and basic::write_file().
Referenced by power_network::power_flow_results_print().
power_supplier_settlement_print()
void local::power_supplier_settlement_print (power_market::market_whole_inform & Power_market_inform)
Definition at line 151 of file agent_output.cpp.
References power_market::market_whole_inform::agent_profiles, agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, output_row_store(), power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, agent::power_supplier::profiles::slack, var_names_set(), agent::power_supplier::profiles::wind, and basic::write_file().
Referenced by agent::agents_results_print().
Simplified_network_print()
void local::Simplified_network_print (power_market::market_inform & Market, std::string name)
Definition at line 8 of file power_market_output.cpp.
References power_market::network_graph::incidence, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::network_graph::power_constraint, and basic::write_file().
Referenced by power_market::Simplified_network_print().
Sink_Node_Set()
void local::Sink_Node_Set (power_market::market_inform & DSO_Market, power_network::DSO_cluster_struct & DSO_cluster)
Definition at line 138 of file DSO.cpp.
References power_network::DSO_cluster_struct::nodes_ID, power_network::DSO_cluster_struct::points_ID, power_market::market_inform::price_intervals, power_market::market_inform::submitted_demand, and power_market::market_inform::submitted_supply.
Referenced by power_market::Filtered_bid_supply_calculation().
Source_Node_Set()
void local::Source_Node_Set (power_market::market_inform & DSO_Market, power_network::DSO_cluster_struct & DSO_cluster)
Definition at line 131 of file DSO.cpp.
References power_network::DSO_cluster_struct::nodes_ID, power_network::DSO_cluster_struct::points_ID, power_market::market_inform::price_intervals, power_market::market_inform::submitted_demand, and power_market::market_inform::submitted_supply.
Referenced by power_market::Filtered_bid_demand_calculation().
var_names_set()
std::vector< std::string > local::var_names_set () inline
Definition at line 6 of file agent_output.cpp.
Referenced by aggregators_settlement_print(), cross_border_settlement_print(), end_users_settlement_print(), industrial_settlement_print(), and power_supplier_settlement_print().