trEnD: power_network Namespace Reference
power_network Namespace Reference
Namespaces
namespace parameters
Classes
struct cbt_struct
Information of cross-border transmission with neighboring nations on the boundary.
struct DSO_cluster_struct
Clustered DSOs in the model.
struct edges_struct
Transmission network edges (power lines) from the power network data.
struct network_inform
struct nodes_struct
Information of nodes on the transmission network.
struct plants_all
Power plants of all types of technologies.
struct plants_per_tech
Power plants of a type of technology.
struct points_struct
Information of spatial points in the model.
struct power_flow_struct
Input parameters and results for power flow analysis.
struct technical_parameters
Technical parameters of the power network.
struct weather_stations_struct
Information of weather stations.
Functions
void HELM_Node_Update (int, network_inform &, power_market::market_whole_inform &)
void HELM_Set (network_inform &, power_market::market_whole_inform &)
void HELM_Solve (int, network_inform &, power_market::market_whole_inform &)
void HELM_Transmission_Set (network_inform &, power_market::market_whole_inform &)
void HELM_Transmission_Solve (int, network_inform &, power_market::market_whole_inform &)
void HELM_Transmission_Update (int, network_inform &, power_market::market_whole_inform &)
void point_distance_cov (points_struct &, double)
void power_flow_results_print (power_market::market_whole_inform &, network_inform &, configuration::process_config &)
void power_network_input_process (network_inform &, std::string parent_dir)
Function Documentation
HELM_Node_Update()
void power_network::HELM_Node_Update (int tick, network_inform & Power_network_inform, power_market::market_whole_inform & Power_market_inform)
Definition at line 870 of file power_flow_analysis.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_network::nodes_struct::bidding_zone, power_market::agent_profiles_struct::cross_border, power_market::agent_profiles_struct::end_user_type, power_market::agent_profiles_struct::end_users, agent::industrial::profiles::HV, agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, power_market::agent_profiles_struct::industrial, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, power_network::points_struct::node, power_network::network_inform::nodes, power_network::power_flow_struct::P_node, power_network::network_inform::points, power_network::network_inform::power_flow, power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, power_network::power_flow_struct::Q_node, agent::power_supplier::profiles::slack, and agent::power_supplier::profiles::wind.
Referenced by power_market::power_market_process_set(), and power_market::power_market_process_update().
HELM_Set()
void power_network::HELM_Set (network_inform & Power_network_inform, power_market::market_whole_inform & Power_market_inform)
Definition at line 569 of file power_flow_analysis.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_network::nodes_struct::bidding_zone, power_network::network_inform::cbt, power_network::power_flow_struct::current_abs, power_network::power_flow_struct::current_arg, power_network::points_struct::distance, power_network::edges_struct::distance, power_network::network_inform::DSO_cluster, power_network::power_flow_struct::edge_admittance, power_network::network_inform::edges, power_network::cbt_struct::entry_bz, power_network::cbt_struct::entry_node_num, power_network::cbt_struct::entry_nodes, power_network::technical_parameters::fraction_dim_distr, power_network::edges_struct::from, spatial_field::geodist(), agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, power_network::technical_parameters::impedenace_base_levels, power_market::market_whole_inform::International_Market, power_network::points_struct::lat, power_network::nodes_struct::lat, power_network::technical_parameters::line_density_conn, power_network::technical_parameters::line_density_distr, power_network::points_struct::lon, power_network::nodes_struct::lon, power_network::power_flow_struct::nodal_admittance, power_network::points_struct::node, power_network::network_inform::nodes, power_network::power_flow_struct::P_node, power_network::network_inform::points, power_market::market_inform::power_flow, power_network::network_inform::power_flow, power_market::agent_profiles_struct::power_supplier, power_network::power_flow_struct::PQ_bus, power_network::power_flow_struct::PU_bus, agent::power_supplier::profiles::pump_storage, power_network::power_flow_struct::Q_node, power_network::power_flow_struct::ref_bus, power_network::power_flow_struct::solver, power_network::network_inform::tech_parameters, power_market::market_inform::time_intervals, power_network::edges_struct::to, power_market::market_whole_inform::TSO_Market, power_network::power_flow_struct::voltage_abs, power_network::power_flow_struct::voltage_arg, power_network::edges_struct::voltage_base, agent::power_supplier::profiles::wind, power_network::technical_parameters::y_conn_shunt, power_network::technical_parameters::y_distr_shunt, power_network::technical_parameters::y_trans_shunt, power_network::technical_parameters::z_base_conn(), power_network::technical_parameters::z_base_distr(), power_network::technical_parameters::z_conn_series, power_network::technical_parameters::z_distr_series, and power_network::technical_parameters::z_trans_series.
Referenced by power_market::power_market_process_set().
HELM_Solve()
void power_network::HELM_Solve (int tick, network_inform & Power_network_inform, power_market::market_whole_inform & Power_market_inform)
Definition at line 995 of file power_flow_analysis.cpp.
References power_network::points_struct::bidding_zone, power_network::nodes_struct::bidding_zone, power_network::power_flow_struct::current_abs, power_network::power_flow_struct::current_arg, power_network::edges_struct::distance, power_network::power_flow_struct::edge_admittance, power_network::network_inform::edges, power_network::edges_struct::from, power_network::points_struct::node, power_network::network_inform::nodes, power_network::power_flow_struct::P_node, power_network::network_inform::points, power_market::market_inform::power_flow, power_network::network_inform::power_flow, power_network::power_flow_struct::PQ_bus, power_network::power_flow_struct::PU_bus, power_network::power_flow_struct::Q_node, power_network::power_flow_struct::ref_bus, power_network::power_flow_struct::solver, power_network::edges_struct::to, power_market::market_whole_inform::TSO_Market, power_network::power_flow_struct::voltage_abs, and power_network::power_flow_struct::voltage_arg.
Referenced by power_market::power_market_process_set(), and power_market::power_market_process_update().
HELM_Transmission_Set()
void power_network::HELM_Transmission_Set (network_inform & Power_network_inform, power_market::market_whole_inform & Power_market_inform)
Definition at line 55 of file power_flow_analysis.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::nodes_struct::bidding_zone, power_network::network_inform::cbt, power_network::power_flow_struct::current_abs, power_network::power_flow_struct::current_arg, power_network::edges_struct::distance, power_network::power_flow_struct::edge_admittance, power_network::network_inform::edges, power_network::cbt_struct::entry_bz, power_network::cbt_struct::entry_node_num, power_network::cbt_struct::entry_nodes, power_network::edges_struct::from, agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, power_network::technical_parameters::impedenace_base_levels, power_market::market_whole_inform::International_Market, power_network::power_flow_struct::nodal_admittance, power_network::points_struct::node, power_network::network_inform::nodes, power_network::power_flow_struct::P_node, power_network::network_inform::points, power_market::market_inform::power_flow, power_market::agent_profiles_struct::power_supplier, power_network::power_flow_struct::PQ_bus, power_network::power_flow_struct::PU_bus, agent::power_supplier::profiles::pump_storage, power_network::power_flow_struct::Q_node, power_network::power_flow_struct::ref_bus, power_network::power_flow_struct::solver, power_network::network_inform::tech_parameters, power_market::market_inform::time_intervals, power_network::edges_struct::to, power_market::market_whole_inform::TSO_Market, power_network::power_flow_struct::voltage_abs, power_network::power_flow_struct::voltage_arg, power_network::edges_struct::voltage_base, agent::power_supplier::profiles::wind, power_network::technical_parameters::y_trans_shunt, and power_network::technical_parameters::z_trans_series.
HELM_Transmission_Solve()
void power_network::HELM_Transmission_Solve (int tick, network_inform & Power_network_inform, power_market::market_whole_inform & Power_market_inform)
Definition at line 378 of file power_flow_analysis.cpp.
References power_network::nodes_struct::bidding_zone, power_network::power_flow_struct::current_abs, power_network::power_flow_struct::current_arg, power_network::edges_struct::distance, power_network::power_flow_struct::edge_admittance, power_network::network_inform::edges, power_network::edges_struct::from, power_network::network_inform::nodes, power_network::power_flow_struct::P_node, power_market::market_inform::power_flow, power_network::power_flow_struct::PQ_bus, power_network::power_flow_struct::PU_bus, power_network::power_flow_struct::Q_node, power_network::power_flow_struct::ref_bus, power_network::power_flow_struct::solver, power_network::edges_struct::to, power_market::market_whole_inform::TSO_Market, power_network::power_flow_struct::voltage_abs, and power_network::power_flow_struct::voltage_arg.
HELM_Transmission_Update()
void power_network::HELM_Transmission_Update (int tick, network_inform & Power_network_inform, power_market::market_whole_inform & Power_market_inform)
Definition at line 259 of file power_flow_analysis.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_network::nodes_struct::bidding_zone, power_market::agent_profiles_struct::cross_border, power_market::agent_profiles_struct::end_user_type, power_market::agent_profiles_struct::end_users, agent::industrial::profiles::HV, agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, power_market::agent_profiles_struct::industrial, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, power_network::points_struct::node, power_network::network_inform::nodes, power_network::power_flow_struct::P_node, power_network::network_inform::points, power_market::market_inform::power_flow, power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, power_network::power_flow_struct::Q_node, power_market::market_whole_inform::TSO_Market, and agent::power_supplier::profiles::wind.
point_distance_cov()
void power_network::point_distance_cov (points_struct & point, double lambda)
Definition at line 192 of file power_network_input.cpp.
References power_network::points_struct::covariance, power_network::points_struct::distance, spatial_field::geodist(), power_network::points_struct::grid_length, power_network::points_struct::lat, and power_network::points_struct::lon.
power_flow_results_print()
void power_network::power_flow_results_print (power_market::market_whole_inform & Power_market_inform, network_inform & Power_network_inform, configuration::process_config & process_par)
Definition at line 56 of file power_flow_output.cpp.
References local::power_flow_transmission_results_print(), local::power_flow_whole_results_print(), and power_market::market_whole_inform::TSO_Market.
Referenced by main().
power_network_input_process()
void power_network::power_network_input_process (network_inform & Power_network_inform, std::string parent_dir)
Definition at line 214 of file power_network_input.cpp.
References power_network::network_inform::edges, basic::get_file_dim(), basic::read_file(), power_network::technical_parameters::set_level_maps(), power_network::network_inform::set_line_density(), and power_network::network_inform::tech_parameters.
Referenced by main().