#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.1                         #
#------------------------------------------------------------------------------#


WORKDIR = $(shell pwd)

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
SEARCHDIR = $(shell pwd)/lib
CFLAGS = -Wall -fopenmp -mavx2 -mfma -DNDEBUG -O3 -s -std=c++2a -I$(WORKDIR) -I$(SEARCHDIR)
RCFLAGS = 
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -fopenmp -s

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -pg -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) -pg
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/trEnD

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS)
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/trEnD

INC_FINAL = $(INC)
CFLAGS_FINAL = $(CFLAGS)
RESINC_FINAL = $(RESINC)
RCFLAGS_FINAL = $(RCFLAGS)
LIBDIR_FINAL = $(LIBDIR)
LIB_FINAL = $(LIB)
LDFLAGS_FINAL = $(LDFLAGS)
OBJDIR_FINAL = .objs
DEP_FINAL = 
OUT_FINAL = $(shell pwd)/trEnD

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/power_market/power_market_output.cpp.o $(OBJDIR_DEBUG)/src/basic/rw_csv.cpp.o $(OBJDIR_DEBUG)/src/configuration/configuration.cpp.o $(OBJDIR_DEBUG)/src/main.cpp.o $(OBJDIR_DEBUG)/src/power_market/DSO.cpp.o $(OBJDIR_DEBUG)/src/power_market/IMO.cpp.o $(OBJDIR_DEBUG)/src/power_market/TSO.cpp.o $(OBJDIR_DEBUG)/src/power_market/power_market_func.cpp.o $(OBJDIR_DEBUG)/src/power_market/power_market_proc.cpp.o $(OBJDIR_DEBUG)/src/power_network/contingency_analysis.cpp.o $(OBJDIR_DEBUG)/src/power_network/power_flow_analysis.cpp.o $(OBJDIR_DEBUG)/src/power_network/power_flow_output.cpp.o $(OBJDIR_DEBUG)/src/power_network/power_network_input.cpp.o $(OBJDIR_DEBUG)/src/spatial_field/geostat.cpp.o $(OBJDIR_DEBUG)/src/spatial_field/spatial_field.cpp.o $(OBJDIR_DEBUG)/src/alglib/ap.cpp.o $(OBJDIR_DEBUG)/src/agent/agent_func.cpp.o $(OBJDIR_DEBUG)/src/agent/agent_output.cpp.o $(OBJDIR_DEBUG)/src/agent/end-user.cpp.o $(OBJDIR_DEBUG)/src/alglib/alglibinternal.cpp.o $(OBJDIR_DEBUG)/src/alglib/alglibmisc.cpp.o $(OBJDIR_DEBUG)/src/alglib/kernels_avx2.cpp.o $(OBJDIR_DEBUG)/src/alglib/kernels_fma.cpp.o $(OBJDIR_DEBUG)/src/alglib/kernels_sse2.cpp.o $(OBJDIR_DEBUG)/src/alglib/linalg.cpp.o $(OBJDIR_DEBUG)/src/alglib/optimization.cpp.o $(OBJDIR_DEBUG)/src/alglib/solvers.cpp.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/power_market/power_market_output.cpp.o $(OBJDIR_RELEASE)/src/basic/rw_csv.cpp.o $(OBJDIR_RELEASE)/src/configuration/configuration.cpp.o $(OBJDIR_RELEASE)/src/main.cpp.o $(OBJDIR_RELEASE)/src/power_market/DSO.cpp.o $(OBJDIR_RELEASE)/src/power_market/IMO.cpp.o $(OBJDIR_RELEASE)/src/power_market/TSO.cpp.o $(OBJDIR_RELEASE)/src/power_market/power_market_func.cpp.o $(OBJDIR_RELEASE)/src/power_market/power_market_proc.cpp.o $(OBJDIR_RELEASE)/src/power_network/contingency_analysis.cpp.o $(OBJDIR_RELEASE)/src/power_network/power_flow_analysis.cpp.o $(OBJDIR_RELEASE)/src/power_network/power_flow_output.cpp.o $(OBJDIR_RELEASE)/src/power_network/power_network_input.cpp.o $(OBJDIR_RELEASE)/src/spatial_field/geostat.cpp.o $(OBJDIR_RELEASE)/src/spatial_field/spatial_field.cpp.o $(OBJDIR_RELEASE)/src/alglib/ap.cpp.o $(OBJDIR_RELEASE)/src/agent/agent_func.cpp.o $(OBJDIR_RELEASE)/src/agent/agent_output.cpp.o $(OBJDIR_RELEASE)/src/agent/end-user.cpp.o $(OBJDIR_RELEASE)/src/alglib/alglibinternal.cpp.o $(OBJDIR_RELEASE)/src/alglib/alglibmisc.cpp.o $(OBJDIR_RELEASE)/src/alglib/kernels_avx2.cpp.o $(OBJDIR_RELEASE)/src/alglib/kernels_fma.cpp.o $(OBJDIR_RELEASE)/src/alglib/kernels_sse2.cpp.o $(OBJDIR_RELEASE)/src/alglib/linalg.cpp.o $(OBJDIR_RELEASE)/src/alglib/optimization.cpp.o $(OBJDIR_RELEASE)/src/alglib/solvers.cpp.o

OBJ_FINAL = $(OBJDIR_FINAL)/src/power_market/power_market_output.cpp.o $(OBJDIR_FINAL)/src/basic/rw_csv.cpp.o $(OBJDIR_FINAL)/src/configuration/configuration.cpp.o $(OBJDIR_FINAL)/src/main.cpp.o $(OBJDIR_FINAL)/src/power_market/DSO.cpp.o $(OBJDIR_FINAL)/src/power_market/IMO.cpp.o $(OBJDIR_FINAL)/src/power_market/TSO.cpp.o $(OBJDIR_FINAL)/src/power_market/power_market_func.cpp.o $(OBJDIR_FINAL)/src/power_market/power_market_proc.cpp.o $(OBJDIR_FINAL)/src/power_network/contingency_analysis.cpp.o $(OBJDIR_FINAL)/src/power_network/power_flow_analysis.cpp.o $(OBJDIR_FINAL)/src/power_network/power_flow_output.cpp.o $(OBJDIR_FINAL)/src/power_network/power_network_input.cpp.o $(OBJDIR_FINAL)/src/spatial_field/geostat.cpp.o $(OBJDIR_FINAL)/src/spatial_field/spatial_field.cpp.o $(OBJDIR_FINAL)/src/alglib/ap.cpp.o $(OBJDIR_FINAL)/src/agent/agent_func.cpp.o $(OBJDIR_FINAL)/src/agent/agent_output.cpp.o $(OBJDIR_FINAL)/src/agent/end-user.cpp.o $(OBJDIR_FINAL)/src/alglib/alglibinternal.cpp.o $(OBJDIR_FINAL)/src/alglib/alglibmisc.cpp.o $(OBJDIR_FINAL)/src/alglib/kernels_avx2.cpp.o $(OBJDIR_FINAL)/src/alglib/kernels_fma.cpp.o $(OBJDIR_FINAL)/src/alglib/kernels_sse2.cpp.o $(OBJDIR_FINAL)/src/alglib/linalg.cpp.o $(OBJDIR_FINAL)/src/alglib/optimization.cpp.o $(OBJDIR_FINAL)/src/alglib/solvers.cpp.o

# all: debug release final
# clean: clean_debug clean_release clean_final

all: final
clean: final

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/power_market || mkdir -p $(OBJDIR_DEBUG)/src/power_market
	test -d $(OBJDIR_DEBUG)/src/basic || mkdir -p $(OBJDIR_DEBUG)/src/basic
	test -d $(OBJDIR_DEBUG)/src/configuration || mkdir -p $(OBJDIR_DEBUG)/src/configuration
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/src/power_network || mkdir -p $(OBJDIR_DEBUG)/src/power_network
	test -d $(OBJDIR_DEBUG)/src/spatial_field || mkdir -p $(OBJDIR_DEBUG)/src/spatial_field
	test -d $(OBJDIR_DEBUG)/src/alglib || mkdir -p $(OBJDIR_DEBUG)/src/alglib
	test -d $(OBJDIR_DEBUG)/src/agent || mkdir -p $(OBJDIR_DEBUG)/src/agent

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/power_market/power_market_output.cpp.o: src/power_market/power_market_output.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_market/power_market_output.cpp -o $(OBJDIR_DEBUG)/src/power_market/power_market_output.cpp.o

$(OBJDIR_DEBUG)/src/basic/rw_csv.cpp.o: src/basic/rw_csv.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/basic/rw_csv.cpp -o $(OBJDIR_DEBUG)/src/basic/rw_csv.cpp.o

$(OBJDIR_DEBUG)/src/configuration/configuration.cpp.o: src/configuration/configuration.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/configuration/configuration.cpp -o $(OBJDIR_DEBUG)/src/configuration/configuration.cpp.o

$(OBJDIR_DEBUG)/src/main.cpp.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.cpp.o

$(OBJDIR_DEBUG)/src/power_market/DSO.cpp.o: src/power_market/DSO.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_market/DSO.cpp -o $(OBJDIR_DEBUG)/src/power_market/DSO.cpp.o

$(OBJDIR_DEBUG)/src/power_market/IMO.cpp.o: src/power_market/IMO.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_market/IMO.cpp -o $(OBJDIR_DEBUG)/src/power_market/IMO.cpp.o

$(OBJDIR_DEBUG)/src/power_market/TSO.cpp.o: src/power_market/TSO.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_market/TSO.cpp -o $(OBJDIR_DEBUG)/src/power_market/TSO.cpp.o

$(OBJDIR_DEBUG)/src/power_market/power_market_func.cpp.o: src/power_market/power_market_func.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_market/power_market_func.cpp -o $(OBJDIR_DEBUG)/src/power_market/power_market_func.cpp.o

$(OBJDIR_DEBUG)/src/power_market/power_market_proc.cpp.o: src/power_market/power_market_proc.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_market/power_market_proc.cpp -o $(OBJDIR_DEBUG)/src/power_market/power_market_proc.cpp.o

$(OBJDIR_DEBUG)/src/power_network/contingency_analysis.cpp.o: src/power_network/contingency_analysis.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_network/contingency_analysis.cpp -o $(OBJDIR_DEBUG)/src/power_network/contingency_analysis.cpp.o

$(OBJDIR_DEBUG)/src/power_network/power_flow_analysis.cpp.o: src/power_network/power_flow_analysis.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_network/power_flow_analysis.cpp -o $(OBJDIR_DEBUG)/src/power_network/power_flow_analysis.cpp.o

$(OBJDIR_DEBUG)/src/power_network/power_flow_output.cpp.o: src/power_network/power_flow_output.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_network/power_flow_output.cpp -o $(OBJDIR_DEBUG)/src/power_network/power_flow_output.cpp.o

$(OBJDIR_DEBUG)/src/power_network/power_network_input.cpp.o: src/power_network/power_network_input.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/power_network/power_network_input.cpp -o $(OBJDIR_DEBUG)/src/power_network/power_network_input.cpp.o

$(OBJDIR_DEBUG)/src/spatial_field/geostat.cpp.o: src/spatial_field/geostat.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/spatial_field/geostat.cpp -o $(OBJDIR_DEBUG)/src/spatial_field/geostat.cpp.o

$(OBJDIR_DEBUG)/src/spatial_field/spatial_field.cpp.o: src/spatial_field/spatial_field.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/spatial_field/spatial_field.cpp -o $(OBJDIR_DEBUG)/src/spatial_field/spatial_field.cpp.o

$(OBJDIR_DEBUG)/src/alglib/ap.cpp.o: src/alglib/ap.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/ap.cpp -o $(OBJDIR_DEBUG)/src/alglib/ap.cpp.o

$(OBJDIR_DEBUG)/src/agent/agent_func.cpp.o: src/agent/agent_func.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/agent/agent_func.cpp -o $(OBJDIR_DEBUG)/src/agent/agent_func.cpp.o

$(OBJDIR_DEBUG)/src/agent/agent_output.cpp.o: src/agent/agent_output.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/agent/agent_output.cpp -o $(OBJDIR_DEBUG)/src/agent/agent_output.cpp.o

$(OBJDIR_DEBUG)/src/agent/end-user.cpp.o: src/agent/end-user.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/agent/end-user.cpp -o $(OBJDIR_DEBUG)/src/agent/end-user.cpp.o

$(OBJDIR_DEBUG)/src/alglib/alglibinternal.cpp.o: src/alglib/alglibinternal.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/alglibinternal.cpp -o $(OBJDIR_DEBUG)/src/alglib/alglibinternal.cpp.o

$(OBJDIR_DEBUG)/src/alglib/alglibmisc.cpp.o: src/alglib/alglibmisc.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/alglibmisc.cpp -o $(OBJDIR_DEBUG)/src/alglib/alglibmisc.cpp.o

$(OBJDIR_DEBUG)/src/alglib/kernels_avx2.cpp.o: src/alglib/kernels_avx2.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/kernels_avx2.cpp -o $(OBJDIR_DEBUG)/src/alglib/kernels_avx2.cpp.o

$(OBJDIR_DEBUG)/src/alglib/kernels_fma.cpp.o: src/alglib/kernels_fma.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/kernels_fma.cpp -o $(OBJDIR_DEBUG)/src/alglib/kernels_fma.cpp.o

$(OBJDIR_DEBUG)/src/alglib/kernels_sse2.cpp.o: src/alglib/kernels_sse2.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/kernels_sse2.cpp -o $(OBJDIR_DEBUG)/src/alglib/kernels_sse2.cpp.o

$(OBJDIR_DEBUG)/src/alglib/linalg.cpp.o: src/alglib/linalg.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/linalg.cpp -o $(OBJDIR_DEBUG)/src/alglib/linalg.cpp.o

$(OBJDIR_DEBUG)/src/alglib/optimization.cpp.o: src/alglib/optimization.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/optimization.cpp -o $(OBJDIR_DEBUG)/src/alglib/optimization.cpp.o

$(OBJDIR_DEBUG)/src/alglib/solvers.cpp.o: src/alglib/solvers.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/alglib/solvers.cpp -o $(OBJDIR_DEBUG)/src/alglib/solvers.cpp.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/power_market
	rm -rf $(OBJDIR_DEBUG)/src/basic
	rm -rf $(OBJDIR_DEBUG)/src/configuration
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/src/power_network
	rm -rf $(OBJDIR_DEBUG)/src/spatial_field
	rm -rf $(OBJDIR_DEBUG)/src/alglib
	rm -rf $(OBJDIR_DEBUG)/src/agent

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/power_market || mkdir -p $(OBJDIR_RELEASE)/src/power_market
	test -d $(OBJDIR_RELEASE)/src/basic || mkdir -p $(OBJDIR_RELEASE)/src/basic
	test -d $(OBJDIR_RELEASE)/src/configuration || mkdir -p $(OBJDIR_RELEASE)/src/configuration
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/src/power_network || mkdir -p $(OBJDIR_RELEASE)/src/power_network
	test -d $(OBJDIR_RELEASE)/src/spatial_field || mkdir -p $(OBJDIR_RELEASE)/src/spatial_field
	test -d $(OBJDIR_RELEASE)/src/alglib || mkdir -p $(OBJDIR_RELEASE)/src/alglib
	test -d $(OBJDIR_RELEASE)/src/agent || mkdir -p $(OBJDIR_RELEASE)/src/agent

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/power_market/power_market_output.cpp.o: src/power_market/power_market_output.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_market/power_market_output.cpp -o $(OBJDIR_RELEASE)/src/power_market/power_market_output.cpp.o

$(OBJDIR_RELEASE)/src/basic/rw_csv.cpp.o: src/basic/rw_csv.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/basic/rw_csv.cpp -o $(OBJDIR_RELEASE)/src/basic/rw_csv.cpp.o

$(OBJDIR_RELEASE)/src/configuration/configuration.cpp.o: src/configuration/configuration.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/configuration/configuration.cpp -o $(OBJDIR_RELEASE)/src/configuration/configuration.cpp.o

$(OBJDIR_RELEASE)/src/main.cpp.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.cpp.o

$(OBJDIR_RELEASE)/src/power_market/DSO.cpp.o: src/power_market/DSO.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_market/DSO.cpp -o $(OBJDIR_RELEASE)/src/power_market/DSO.cpp.o

$(OBJDIR_RELEASE)/src/power_market/IMO.cpp.o: src/power_market/IMO.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_market/IMO.cpp -o $(OBJDIR_RELEASE)/src/power_market/IMO.cpp.o

$(OBJDIR_RELEASE)/src/power_market/TSO.cpp.o: src/power_market/TSO.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_market/TSO.cpp -o $(OBJDIR_RELEASE)/src/power_market/TSO.cpp.o

$(OBJDIR_RELEASE)/src/power_market/power_market_func.cpp.o: src/power_market/power_market_func.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_market/power_market_func.cpp -o $(OBJDIR_RELEASE)/src/power_market/power_market_func.cpp.o

$(OBJDIR_RELEASE)/src/power_market/power_market_proc.cpp.o: src/power_market/power_market_proc.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_market/power_market_proc.cpp -o $(OBJDIR_RELEASE)/src/power_market/power_market_proc.cpp.o

$(OBJDIR_RELEASE)/src/power_network/contingency_analysis.cpp.o: src/power_network/contingency_analysis.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_network/contingency_analysis.cpp -o $(OBJDIR_RELEASE)/src/power_network/contingency_analysis.cpp.o

$(OBJDIR_RELEASE)/src/power_network/power_flow_analysis.cpp.o: src/power_network/power_flow_analysis.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_network/power_flow_analysis.cpp -o $(OBJDIR_RELEASE)/src/power_network/power_flow_analysis.cpp.o

$(OBJDIR_RELEASE)/src/power_network/power_flow_output.cpp.o: src/power_network/power_flow_output.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_network/power_flow_output.cpp -o $(OBJDIR_RELEASE)/src/power_network/power_flow_output.cpp.o

$(OBJDIR_RELEASE)/src/power_network/power_network_input.cpp.o: src/power_network/power_network_input.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/power_network/power_network_input.cpp -o $(OBJDIR_RELEASE)/src/power_network/power_network_input.cpp.o

$(OBJDIR_RELEASE)/src/spatial_field/geostat.cpp.o: src/spatial_field/geostat.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/spatial_field/geostat.cpp -o $(OBJDIR_RELEASE)/src/spatial_field/geostat.cpp.o

$(OBJDIR_RELEASE)/src/spatial_field/spatial_field.cpp.o: src/spatial_field/spatial_field.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/spatial_field/spatial_field.cpp -o $(OBJDIR_RELEASE)/src/spatial_field/spatial_field.cpp.o

$(OBJDIR_RELEASE)/src/alglib/ap.cpp.o: src/alglib/ap.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/ap.cpp -o $(OBJDIR_RELEASE)/src/alglib/ap.cpp.o

$(OBJDIR_RELEASE)/src/agent/agent_func.cpp.o: src/agent/agent_func.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/agent/agent_func.cpp -o $(OBJDIR_RELEASE)/src/agent/agent_func.cpp.o

$(OBJDIR_RELEASE)/src/agent/agent_output.cpp.o: src/agent/agent_output.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/agent/agent_output.cpp -o $(OBJDIR_RELEASE)/src/agent/agent_output.cpp.o

$(OBJDIR_RELEASE)/src/agent/end-user.cpp.o: src/agent/end-user.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/agent/end-user.cpp -o $(OBJDIR_RELEASE)/src/agent/end-user.cpp.o

$(OBJDIR_RELEASE)/src/alglib/alglibinternal.cpp.o: src/alglib/alglibinternal.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/alglibinternal.cpp -o $(OBJDIR_RELEASE)/src/alglib/alglibinternal.cpp.o

$(OBJDIR_RELEASE)/src/alglib/alglibmisc.cpp.o: src/alglib/alglibmisc.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/alglibmisc.cpp -o $(OBJDIR_RELEASE)/src/alglib/alglibmisc.cpp.o

$(OBJDIR_RELEASE)/src/alglib/kernels_avx2.cpp.o: src/alglib/kernels_avx2.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/kernels_avx2.cpp -o $(OBJDIR_RELEASE)/src/alglib/kernels_avx2.cpp.o

$(OBJDIR_RELEASE)/src/alglib/kernels_fma.cpp.o: src/alglib/kernels_fma.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/kernels_fma.cpp -o $(OBJDIR_RELEASE)/src/alglib/kernels_fma.cpp.o

$(OBJDIR_RELEASE)/src/alglib/kernels_sse2.cpp.o: src/alglib/kernels_sse2.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/kernels_sse2.cpp -o $(OBJDIR_RELEASE)/src/alglib/kernels_sse2.cpp.o

$(OBJDIR_RELEASE)/src/alglib/linalg.cpp.o: src/alglib/linalg.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/linalg.cpp -o $(OBJDIR_RELEASE)/src/alglib/linalg.cpp.o

$(OBJDIR_RELEASE)/src/alglib/optimization.cpp.o: src/alglib/optimization.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/optimization.cpp -o $(OBJDIR_RELEASE)/src/alglib/optimization.cpp.o

$(OBJDIR_RELEASE)/src/alglib/solvers.cpp.o: src/alglib/solvers.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/alglib/solvers.cpp -o $(OBJDIR_RELEASE)/src/alglib/solvers.cpp.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/power_market
	rm -rf $(OBJDIR_RELEASE)/src/basic
	rm -rf $(OBJDIR_RELEASE)/src/configuration
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/src/power_network
	rm -rf $(OBJDIR_RELEASE)/src/spatial_field
	rm -rf $(OBJDIR_RELEASE)/src/alglib
	rm -rf $(OBJDIR_RELEASE)/src/agent

before_final: 
	test -d $(OBJDIR_FINAL)/src/power_market || mkdir -p $(OBJDIR_FINAL)/src/power_market
	test -d $(OBJDIR_FINAL)/src/basic || mkdir -p $(OBJDIR_FINAL)/src/basic
	test -d $(OBJDIR_FINAL)/src/configuration || mkdir -p $(OBJDIR_FINAL)/src/configuration
	test -d $(OBJDIR_FINAL)/src || mkdir -p $(OBJDIR_FINAL)/src
	test -d $(OBJDIR_FINAL)/src/power_network || mkdir -p $(OBJDIR_FINAL)/src/power_network
	test -d $(OBJDIR_FINAL)/src/spatial_field || mkdir -p $(OBJDIR_FINAL)/src/spatial_field
	test -d $(OBJDIR_FINAL)/src/alglib || mkdir -p $(OBJDIR_FINAL)/src/alglib
	test -d $(OBJDIR_FINAL)/src/agent || mkdir -p $(OBJDIR_FINAL)/src/agent

after_final: 

final: before_final out_final after_final

out_final: before_final $(OBJ_FINAL) $(DEP_FINAL)
	$(LD) $(LIBDIR_FINAL) -o $(OUT_FINAL) $(OBJ_FINAL)  $(LDFLAGS_FINAL) $(LIB_FINAL)

$(OBJDIR_FINAL)/src/power_market/power_market_output.cpp.o: src/power_market/power_market_output.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_market/power_market_output.cpp -o $(OBJDIR_FINAL)/src/power_market/power_market_output.cpp.o

$(OBJDIR_FINAL)/src/basic/rw_csv.cpp.o: src/basic/rw_csv.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/basic/rw_csv.cpp -o $(OBJDIR_FINAL)/src/basic/rw_csv.cpp.o

$(OBJDIR_FINAL)/src/configuration/configuration.cpp.o: src/configuration/configuration.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/configuration/configuration.cpp -o $(OBJDIR_FINAL)/src/configuration/configuration.cpp.o

$(OBJDIR_FINAL)/src/main.cpp.o: src/main.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/main.cpp -o $(OBJDIR_FINAL)/src/main.cpp.o

$(OBJDIR_FINAL)/src/power_market/DSO.cpp.o: src/power_market/DSO.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_market/DSO.cpp -o $(OBJDIR_FINAL)/src/power_market/DSO.cpp.o

$(OBJDIR_FINAL)/src/power_market/IMO.cpp.o: src/power_market/IMO.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_market/IMO.cpp -o $(OBJDIR_FINAL)/src/power_market/IMO.cpp.o

$(OBJDIR_FINAL)/src/power_market/TSO.cpp.o: src/power_market/TSO.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_market/TSO.cpp -o $(OBJDIR_FINAL)/src/power_market/TSO.cpp.o

$(OBJDIR_FINAL)/src/power_market/power_market_func.cpp.o: src/power_market/power_market_func.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_market/power_market_func.cpp -o $(OBJDIR_FINAL)/src/power_market/power_market_func.cpp.o

$(OBJDIR_FINAL)/src/power_market/power_market_proc.cpp.o: src/power_market/power_market_proc.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_market/power_market_proc.cpp -o $(OBJDIR_FINAL)/src/power_market/power_market_proc.cpp.o

$(OBJDIR_FINAL)/src/power_network/contingency_analysis.cpp.o: src/power_network/contingency_analysis.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_network/contingency_analysis.cpp -o $(OBJDIR_FINAL)/src/power_network/contingency_analysis.cpp.o

$(OBJDIR_FINAL)/src/power_network/power_flow_analysis.cpp.o: src/power_network/power_flow_analysis.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_network/power_flow_analysis.cpp -o $(OBJDIR_FINAL)/src/power_network/power_flow_analysis.cpp.o

$(OBJDIR_FINAL)/src/power_network/power_flow_output.cpp.o: src/power_network/power_flow_output.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_network/power_flow_output.cpp -o $(OBJDIR_FINAL)/src/power_network/power_flow_output.cpp.o

$(OBJDIR_FINAL)/src/power_network/power_network_input.cpp.o: src/power_network/power_network_input.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/power_network/power_network_input.cpp -o $(OBJDIR_FINAL)/src/power_network/power_network_input.cpp.o

$(OBJDIR_FINAL)/src/spatial_field/geostat.cpp.o: src/spatial_field/geostat.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/spatial_field/geostat.cpp -o $(OBJDIR_FINAL)/src/spatial_field/geostat.cpp.o

$(OBJDIR_FINAL)/src/spatial_field/spatial_field.cpp.o: src/spatial_field/spatial_field.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/spatial_field/spatial_field.cpp -o $(OBJDIR_FINAL)/src/spatial_field/spatial_field.cpp.o

$(OBJDIR_FINAL)/src/alglib/ap.cpp.o: src/alglib/ap.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/ap.cpp -o $(OBJDIR_FINAL)/src/alglib/ap.cpp.o

$(OBJDIR_FINAL)/src/agent/agent_func.cpp.o: src/agent/agent_func.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/agent/agent_func.cpp -o $(OBJDIR_FINAL)/src/agent/agent_func.cpp.o

$(OBJDIR_FINAL)/src/agent/agent_output.cpp.o: src/agent/agent_output.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/agent/agent_output.cpp -o $(OBJDIR_FINAL)/src/agent/agent_output.cpp.o

$(OBJDIR_FINAL)/src/agent/end-user.cpp.o: src/agent/end-user.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/agent/end-user.cpp -o $(OBJDIR_FINAL)/src/agent/end-user.cpp.o

$(OBJDIR_FINAL)/src/alglib/alglibinternal.cpp.o: src/alglib/alglibinternal.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/alglibinternal.cpp -o $(OBJDIR_FINAL)/src/alglib/alglibinternal.cpp.o

$(OBJDIR_FINAL)/src/alglib/alglibmisc.cpp.o: src/alglib/alglibmisc.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/alglibmisc.cpp -o $(OBJDIR_FINAL)/src/alglib/alglibmisc.cpp.o

$(OBJDIR_FINAL)/src/alglib/kernels_avx2.cpp.o: src/alglib/kernels_avx2.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/kernels_avx2.cpp -o $(OBJDIR_FINAL)/src/alglib/kernels_avx2.cpp.o

$(OBJDIR_FINAL)/src/alglib/kernels_fma.cpp.o: src/alglib/kernels_fma.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/kernels_fma.cpp -o $(OBJDIR_FINAL)/src/alglib/kernels_fma.cpp.o

$(OBJDIR_FINAL)/src/alglib/kernels_sse2.cpp.o: src/alglib/kernels_sse2.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/kernels_sse2.cpp -o $(OBJDIR_FINAL)/src/alglib/kernels_sse2.cpp.o

$(OBJDIR_FINAL)/src/alglib/linalg.cpp.o: src/alglib/linalg.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/linalg.cpp -o $(OBJDIR_FINAL)/src/alglib/linalg.cpp.o

$(OBJDIR_FINAL)/src/alglib/optimization.cpp.o: src/alglib/optimization.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/optimization.cpp -o $(OBJDIR_FINAL)/src/alglib/optimization.cpp.o

$(OBJDIR_FINAL)/src/alglib/solvers.cpp.o: src/alglib/solvers.cpp
	$(CXX) $(CFLAGS_FINAL) $(INC_FINAL) -c src/alglib/solvers.cpp -o $(OBJDIR_FINAL)/src/alglib/solvers.cpp.o

clean_final: 
	rm -f $(OBJ_FINAL) $(OUT_FINAL)
	rm -rf $(OBJDIR_FINAL)/src/power_market
	rm -rf $(OBJDIR_FINAL)/src/basic
	rm -rf $(OBJDIR_FINAL)/src/configuration
	rm -rf $(OBJDIR_FINAL)/src
	rm -rf $(OBJDIR_FINAL)/src/power_network
	rm -rf $(OBJDIR_FINAL)/src/spatial_field
	rm -rf $(OBJDIR_FINAL)/src/alglib
	rm -rf $(OBJDIR_FINAL)/src/agent

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release before_final after_final clean_final

