trEnD: area_demand.cpp File Reference
area_demand.cpp File Reference
#include <iostream>
#include <chrono>
#include <boost/math/distributions/normal.hpp>
#include "../basic/Basic_Definitions.h"
#include "Geostat.h"
#include "../basic/rw_csv.h"
Functions
int main ()
boost::math::normal norm_dist (0.0, 1.0)
Function Documentation
main()
int main ()
Definition at line 11 of file area_demand.cpp.
References spatial_field::geodist(), norm_dist(), basic::read_file(), and basic::write_file().
norm_dist()
boost::math::normal norm_dist (0. 0, 1. 0)
Referenced by main().