trEnD: spatial_field Namespace Reference
spatial_field Namespace Reference
Classes
class Earth_Constant
struct estimation_inform
struct fin_field
Functions
void demand_imbalance_estimation (power_network::network_inform &, power_market::market_inform &, configuration::process_config &)
double geodist (Eigen::Vector2d, Eigen::Vector2d)
void solar_radiation_estimation (power_network::network_inform &, configuration::process_config &)
void spatial_field_store (power_network::network_inform &, fin_field, configuration::process_config &, int)
void wind_on_cf_estimation (power_network::network_inform &, configuration::process_config &)
Function Documentation
demand_imbalance_estimation()
void spatial_field::demand_imbalance_estimation (power_network::network_inform & Power_network_inform, power_market::market_inform & International_Market, configuration::process_config & process_par)
Definition at line 78 of file spatial_field.cpp.
References spatial_field::estimation_inform::alpha_iteration, power_network::points_struct::bidding_zone, local::BME_copula(), local::BME_linear(), spatial_field::estimation_inform::Conversion_Mat_1, spatial_field::estimation_inform::Conversion_Mat_2, power_network::points_struct::covariance, power_market::market_inform::demand_default, basic::get_file_dim(), spatial_field::estimation_inform::mu, spatial_field::estimation_inform::mu_mean, spatial_field::estimation_inform::mu_scale, spatial_field::estimation_inform::norm_dist, power_network::points_struct::point_area, power_network::network_inform::points, power_network::points_struct::population_density, basic::read_file(), configuration::process_config::time_boundary, configuration::process_config::total_time, basic::write_file(), spatial_field::estimation_inform::x, and spatial_field::estimation_inform::x_scale.
Referenced by main().
geodist()
double spatial_field::geodist (Eigen::Vector2d P_1, Eigen::Vector2d P_2)
Definition at line 33 of file geostat.cpp.
References spatial_field::Earth_Constant::Earth_Ecc, and spatial_field::Earth_Constant::Earth_Radius_short.
Referenced by power_market::DSO_Markets_Set(), power_network::HELM_Set(), and power_network::point_distance_cov().
solar_radiation_estimation()
void spatial_field::solar_radiation_estimation (power_network::network_inform & Power_network_inform, configuration::process_config & process_par)
Definition at line 369 of file spatial_field.cpp.
References spatial_field::estimation_inform::alpha_iteration, power_network::points_struct::bidding_zone, local::BME_copula(), basic::get_file_dim(), spatial_field::estimation_inform::mu, spatial_field::estimation_inform::mu_mean, spatial_field::estimation_inform::mu_scale, spatial_field::estimation_inform::norm_dist, power_network::weather_stations_struct::point, power_network::network_inform::points, basic::read_file(), configuration::process_config::time_boundary, configuration::process_config::total_time, power_network::network_inform::weather_stations, basic::write_file(), spatial_field::estimation_inform::x, and spatial_field::estimation_inform::x_scale.
Referenced by main().
spatial_field_store()
void spatial_field::spatial_field_store (power_network::network_inform & Power_network_inform, fin_field fin_field_processed, configuration::process_config & process_par, int Time)
Definition at line 545 of file spatial_field.cpp.
References power_network::points_struct::bidding_zone, spatial_field::fin_field::demand, spatial_field::fin_field::imbalance, power_network::points_struct::imbalance_field, power_network::points_struct::nominal_mean_demand_field, power_network::network_inform::points, basic::read_file(), spatial_field::fin_field::solar, power_network::points_struct::solar_cf, configuration::process_config::time_boundary, spatial_field::fin_field::wind_on, and power_network::points_struct::wind_on_cf.
Referenced by power_market::power_market_process_set().
wind_on_cf_estimation()
void spatial_field::wind_on_cf_estimation (power_network::network_inform & Power_network_inform, configuration::process_config & process_par)
Definition at line 242 of file spatial_field.cpp.
References spatial_field::estimation_inform::alpha_iteration, power_network::points_struct::bidding_zone, local::BME_copula(), power_network::plants_per_tech::cap, power_network::points_struct::coordinate_grid, basic::get_file_dim(), power_network::points_struct::grid_length, spatial_field::estimation_inform::mu, spatial_field::estimation_inform::mu_mean, spatial_field::estimation_inform::mu_scale, power_network::plants_per_tech::node, spatial_field::estimation_inform::norm_dist, power_network::network_inform::plants, power_network::network_inform::points, basic::read_file(), configuration::process_config::time_boundary, configuration::process_config::total_time, power_network::plants_all::wind, basic::write_file(), power_network::points_struct::x, power_network::plants_per_tech::x, spatial_field::estimation_inform::x, spatial_field::estimation_inform::x_scale, power_network::points_struct::y, and power_network::plants_per_tech::y.
Referenced by main().