trEnD: agent Namespace Reference
agent Namespace Reference
Namespaces
namespace aggregator
namespace cross_border
namespace end_user
namespace industrial
namespace parameters
namespace power_supplier
Classes
struct bids
struct results
struct settlement
struct settlement_process
Functions
void agents_balancing_update (int, power_market::market_whole_inform &, power_network::network_inform &)
void agents_filter_demand_update (int, power_market::market_whole_inform &, power_network::network_inform &)
void agents_filter_supply_update (int, power_market::market_whole_inform &, power_network::network_inform &)
void agents_redispatch_update (int, power_market::market_whole_inform &, power_network::network_inform &)
void agents_results_print (power_market::market_whole_inform &, power_network::network_inform &)
void agents_set (int, power_market::market_whole_inform &, power_network::network_inform &)
void agents_status_update (int, power_market::market_whole_inform &, power_network::network_inform &, bool)
void agents_submit_update (int, power_market::market_whole_inform &, power_network::network_inform &)
Function Documentation
agents_balancing_update()
void agent::agents_balancing_update (int tick, power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 2385 of file agent_func.cpp.
agents_filter_demand_update()
void agent::agents_filter_demand_update (int tick, power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 2375 of file agent_func.cpp.
agents_filter_supply_update()
void agent::agents_filter_supply_update (int tick, power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 2380 of file agent_func.cpp.
agents_redispatch_update()
void agent::agents_redispatch_update (int tick, power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 2370 of file agent_func.cpp.
agents_results_print()
void agent::agents_results_print (power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 208 of file agent_output.cpp.
References local::aggregators_settlement_print(), local::cross_border_settlement_print(), local::end_users_settlement_print(), local::industrial_settlement_print(), and local::power_supplier_settlement_print().
Referenced by main().
agents_set()
void agent::agents_set (int start_time, power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 2362 of file agent_func.cpp.
References power_market::market_whole_inform::agent_profiles, power_market::agent_profiles::aggregators, power_market::agent_profiles::cross_border, power_market::agent_profiles::end_users, power_market::agent_profiles::industrial, power_market::market_whole_inform::International_Market, and power_market::agent_profiles::power_supplier.
agents_status_update()
void agent::agents_status_update (int tick, power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform, bool control_reserve_flag)
Definition at line 2393 of file agent_func.cpp.
agents_submit_update()
void agent::agents_submit_update (int tick, power_market::market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 2401 of file agent_func.cpp.