trEnD: end-user.cpp File Reference
end-user.cpp File Reference
#include <iostream>
#include "../basic/Basic_Definitions.h"
#include "../basic/LP_gpa_fast.cpp"
Classes
struct end_user_decision
struct end_user_operation
struct EV_inform
struct smart_appliance_inform
struct sorted_vector
struct storage_inform
Functions
void EV_schedule (Eigen::VectorXd subscept_tariff, EV_inform &result)
int main ()
void smart_appliance_schedule (sorted_vector sorted_tariff, Eigen::VectorXd normalized_default_demand_profile, double residual_unfulfilled_demand, smart_appliance_inform &result)
sorted_vector sort (Eigen::VectorXd original)
void storage_schedule_LP (Eigen::VectorXd subscept_tariff, storage_inform &result, bool fixed_end=0)
void storage_schedule_naive (sorted_vector sorted_tariff, storage_inform &result)
Class Documentation
end_user_decision
struct end_user_decision
Definition at line 8 of file end-user.cpp.
Class Members
bool active_flex
bool dynamic_tariff
bool EV_self_charging
bool PV_BESS
bool reverse_flow
bool smart_appliance
end_user_operation
struct end_user_operation
Definition at line 49 of file end-user.cpp.
Class Members
storage_inform BESS
end_user_decision decision
EV_inform EV
VectorXd normalized_default_demand_profile
VectorXd normalized_default_PV_profile
VectorXd normalized_scheduled_neg_cr_profile
VectorXd normalized_scheduled_pos_cr_profile
VectorXd normalized_scheduled_residual_demand_flex_profile
VectorXd normalized_scheduled_residual_demand_inflex_profile
int point_ID
double PV_scale
smart_appliance_inform smart_appliance
EV_inform
struct EV_inform
Definition at line 39 of file end-user.cpp.
Class Members
storage_inform BESS
double energy_demand
VectorXi house_default_period
VectorXi usage_default_period
smart_appliance_inform
struct smart_appliance_inform
Definition at line 17 of file end-user.cpp.
Class Members
double flexibility_factor
VectorXd normalized_scheduled_profile
double scale
sorted_vector
struct sorted_vector
Definition at line 69 of file end-user.cpp.
Class Members
VectorXi id
VectorXd value
storage_inform
struct storage_inform
Definition at line 26 of file end-user.cpp.
Class Members
double capacity_scale
double efficiency
double energy_scale
VectorXd normalized_scheduled_capacity_profile
VectorXd normalized_scheduled_soc_profile
double soc_final
double soc_ini
Function Documentation
EV_schedule()
void EV_schedule (Eigen::VectorXd subscept_tariff, EV_inform & result)
Definition at line 326 of file end-user.cpp.
References EV_inform::BESS, storage_inform::energy_scale, EV_inform::house_default_period, storage_inform::soc_final, sort(), and storage_schedule_LP().
Referenced by main().
main()
int main ()
Definition at line 341 of file end-user.cpp.
References EV_inform::BESS, end_user_operation::BESS, storage_inform::capacity_scale, storage_inform::efficiency, EV_inform::energy_demand, storage_inform::energy_scale, end_user_operation::EV, EV_schedule(), smart_appliance_inform::flexibility_factor, EV_inform::house_default_period, end_user_operation::normalized_default_demand_profile, storage_inform::normalized_scheduled_capacity_profile, smart_appliance_inform::scale, end_user_operation::smart_appliance, smart_appliance_schedule(), storage_inform::soc_final, storage_inform::soc_ini, sort(), storage_schedule_LP(), storage_schedule_naive(), and EV_inform::usage_default_period.
smart_appliance_schedule()
void smart_appliance_schedule (sorted_vector sorted_tariff, Eigen::VectorXd normalized_default_demand_profile, double residual_unfulfilled_demand, smart_appliance_inform & result)
Definition at line 92 of file end-user.cpp.
References smart_appliance_inform::flexibility_factor, sorted_vector::id, smart_appliance_inform::normalized_scheduled_profile, and smart_appliance_inform::scale.
Referenced by main().
sort()
sorted_vector sort (Eigen::VectorXd original)
Definition at line 74 of file end-user.cpp.
References sorted_vector::id, sort(), and sorted_vector::value.
Referenced by EV_schedule(), main(), and sort().
storage_schedule_LP()
void storage_schedule_LP (Eigen::VectorXd subscept_tariff, storage_inform & result, bool fixed_end = 0)
Definition at line 109 of file end-user.cpp.
References LP_object::Boundary, storage_inform::capacity_scale, LP_object::Constraint, LP_object::Constraints_eq_num, LP_object::Constraints_ie_num, storage_inform::efficiency, storage_inform::energy_scale, LP_constraint::eq_orig_matrix, LP_boundary::eq_vector, LP_constraint::ie_orig_matrix, LP_boundary::ie_orig_matrix, LP_process(), storage_inform::normalized_scheduled_capacity_profile, storage_inform::normalized_scheduled_soc_profile, LP_object::Objective, LP_objective::orig_vector, LP_solution::orig_vector, storage_inform::soc_final, storage_inform::soc_ini, LP_object::Solution, and LP_object::Variables_num.
Referenced by EV_schedule(), and main().
storage_schedule_naive()
void storage_schedule_naive (sorted_vector sorted_tariff, storage_inform & result)
Definition at line 213 of file end-user.cpp.
References storage_inform::capacity_scale, storage_inform::efficiency, storage_inform::energy_scale, sorted_vector::id, storage_inform::normalized_scheduled_capacity_profile, storage_inform::normalized_scheduled_soc_profile, storage_inform::soc_final, storage_inform::soc_ini, and sorted_vector::value.
Referenced by main().