trEnD: power_market Namespace Reference
power_market Namespace Reference
Namespaces
namespace parameters
Classes
struct agent_profiles_struct
struct fin_market
struct market_inform
struct market_whole_inform
struct network_graph
struct results
struct schedule
struct schedules
struct settlement
Typedefs
typedef std::vector< market_inform > markets_inform
typedef std::vector< alglib::minlpstate > Problems
Functions
void Balancing_bid_calculation (int, market_whole_inform &, power_network::network_inform &)
void Confirmed_bid_calculation (int, market_whole_inform &, power_network::network_inform &)
void default_demand_set (power_network::network_inform &, market_whole_inform &, int)
void DSO_Market_Results_Get (int, market_inform &, power_network::DSO_cluster_struct &, bool supply=1)
void DSO_Markets_Set (markets_inform &, power_network::network_inform &, int)
void Filtered_bid_demand_calculation (int, market_whole_inform &, power_network::network_inform &)
void Filtered_bid_supply_calculation (int, market_whole_inform &, power_network::network_inform &)
void Flow_Based_Market_LP_Set (market_inform &)
void Flow_Based_Market_Optimization (market_inform &)
void International_Market_Optimization (int, market_inform &)
void International_Market_Price_Estimation (int, market_inform &, power_network::network_inform &, configuration::process_config &)
void International_Market_Set (market_inform &, power_network::network_inform &, int, fin_market)
void Market_Initialization (market_inform &)
void Markets_results_print (market_whole_inform &, configuration::process_config &)
void Operation_Initialization (market_inform &, int)
void power_market_process_set (power_network::network_inform &, market_whole_inform &, configuration::process_config &)
void power_market_process_update (power_network::network_inform &, market_whole_inform &, configuration::process_config &)
void Simplified_network_print (market_whole_inform &)
void Submitted_bid_calculation (market_whole_inform &, power_network::network_inform &)
void TSO_Market_Actual_Results_Get (int, market_inform &)
void TSO_Market_Scheduled_Results_Get (int, market_inform &)
void TSO_Market_Set (market_inform &, power_network::network_inform &, int)
Typedef Documentation
markets_inform
typedef std::vector<market_inform> power_market::markets_inform
A vector of power markets. This type is used in setting the DSO markets.
Definition at line 208 of file power_market.h.
Problems
typedef std::vector<alglib::minlpstate> power_market::Problems
A vector of LP problems of power markets. This type is used in setting the LP for DSO markets.
Definition at line 211 of file power_market.h.
Function Documentation
Balancing_bid_calculation()
void power_market::Balancing_bid_calculation (int tick, market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 278 of file TSO.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_market::agent_profiles_struct::cross_border, power_market::agent_profiles_struct::end_users, agent::industrial::profiles::HV, agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, power_market::agent_profiles_struct::industrial, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, Market_Initialization(), power_network::points_struct::node, power_network::network_inform::points, power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, agent::power_supplier::profiles::slack, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, power_market::market_whole_inform::TSO_Market, and agent::power_supplier::profiles::wind.
Referenced by power_market_process_set(), and power_market_process_update().
Confirmed_bid_calculation()
void power_market::Confirmed_bid_calculation (int tick, market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 98 of file TSO.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_market::agent_profiles_struct::cross_border, power_market::agent_profiles_struct::end_users, agent::industrial::profiles::HV, agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, power_market::agent_profiles_struct::industrial, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, Market_Initialization(), power_network::points_struct::node, power_network::network_inform::points, power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, agent::power_supplier::profiles::slack, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, power_market::market_whole_inform::TSO_Market, and agent::power_supplier::profiles::wind.
Referenced by power_market_process_set(), and power_market_process_update().
default_demand_set()
void power_market::default_demand_set (power_network::network_inform & Power_network_inform, market_whole_inform & Power_market_inform, int Time)
Definition at line 7 of file power_market_proc.cpp.
References power_market::fin_market::cbt, power_market::fin_market::demand, power_market::fin_market::dir, power_market::market_whole_inform::International_Market, International_Market_Set(), power_market::fin_market::moc, power_market::fin_market::solar, power_market::fin_market::wind_off, and power_market::fin_market::wind_on.
Referenced by main().
DSO_Market_Results_Get()
void power_market::DSO_Market_Results_Get (int tick, market_inform & Market, power_network::DSO_cluster_struct & DSO_cluster, bool supply = 1)
Definition at line 271 of file DSO.cpp.
References power_market::parameters::price_ID_bimap::bidded_price, power_market::market_inform::bidded_price_map, power_market::market_inform::confirmed, power_market::results::demand, power_market::market_inform::network, power_market::network_graph::num_vertice, power_network::DSO_cluster_struct::points_ID, power_market::results::price, power_market::market_inform::price_intervals, power_market::market_inform::Problem, power_market::results::ratio_demand, power_market::results::ratio_supply, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, and power_market::results::supply.
Referenced by Filtered_bid_demand_calculation(), and Filtered_bid_supply_calculation().
DSO_Markets_Set()
void power_market::DSO_Markets_Set (markets_inform & DSO_Markets, power_network::network_inform & Power_network_inform, int Time)
Definition at line 7 of file DSO.cpp.
References power_market::parameters::bidded_price(), power_network::points_struct::distance, power_network::network_inform::DSO_cluster, power_network::technical_parameters::fraction_dim_distr, spatial_field::geodist(), power_network::nodes_struct::in_cluster_ID, power_network::points_struct::lat, power_network::nodes_struct::lat, power_network::technical_parameters::line_density_conn, power_network::technical_parameters::line_density_distr, power_network::points_struct::lon, power_network::nodes_struct::lon, Market_Initialization(), power_network::points_struct::node, power_network::network_inform::nodes, power_network::network_inform::points, power_network::technical_parameters::power_limit_conn, power_network::technical_parameters::power_limit_distr, power_network::technical_parameters::s_base, power_network::network_inform::tech_parameters, power_network::technical_parameters::theta_distr_limit, power_network::technical_parameters::voltage_cutoff_conn, power_network::technical_parameters::voltage_cutoff_distr, power_network::technical_parameters::z_base_conn(), power_network::technical_parameters::z_base_distr(), power_network::technical_parameters::z_conn_series, and power_network::technical_parameters::z_distr_series.
Referenced by power_market_process_set().
Filtered_bid_demand_calculation()
void power_market::Filtered_bid_demand_calculation (int tick, market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 146 of file DSO.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_network::nodes_struct::cluster, power_network::network_inform::DSO_cluster, DSO_Market_Results_Get(), power_market::market_whole_inform::DSO_Markets, power_market::agent_profiles_struct::end_users, Flow_Based_Market_Optimization(), power_network::points_struct::in_cluster_ID, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, Market_Initialization(), power_network::points_struct::node, power_network::network_inform::nodes, power_network::network_inform::points, power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, agent::power_supplier::profiles::slack, and local::Source_Node_Set().
Referenced by power_market_process_set(), and power_market_process_update().
Filtered_bid_supply_calculation()
void power_market::Filtered_bid_supply_calculation (int tick, market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 204 of file DSO.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_network::nodes_struct::cluster, power_network::network_inform::DSO_cluster, DSO_Market_Results_Get(), power_market::market_whole_inform::DSO_Markets, power_market::agent_profiles_struct::end_users, Flow_Based_Market_Optimization(), agent::power_supplier::profiles::hydro, power_network::points_struct::in_cluster_ID, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, Market_Initialization(), power_network::points_struct::node, power_network::network_inform::nodes, power_network::network_inform::points, power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, local::Sink_Node_Set(), and agent::power_supplier::profiles::wind.
Referenced by power_market_process_set(), and power_market_process_update().
Flow_Based_Market_LP_Set()
void power_market::Flow_Based_Market_LP_Set (market_inform & Market)
Definition at line 69 of file power_market_func.cpp.
References power_market::network_graph::admittance, power_market::parameters::price_ID_bimap::bidded_price, power_market::market_inform::bidded_price_map, power_market::network_graph::incidence, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::network_graph::num_vertice, power_market::network_graph::power_constraint, power_market::market_inform::price_intervals, power_market::market_inform::Problem, and power_market::network_graph::voltage_constraint.
Referenced by power_market_process_set().
Flow_Based_Market_Optimization()
void power_market::Flow_Based_Market_Optimization (market_inform & Market)
Definition at line 210 of file power_market_func.cpp.
References power_market::parameters::price_ID_bimap::bidded_price, power_market::market_inform::bidded_price_map, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::network_graph::num_vertice, power_market::network_graph::power_constraint, power_market::market_inform::price_intervals, power_market::market_inform::Problem, power_market::market_inform::reference_price, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, and power_market::network_graph::voltage_constraint.
Referenced by Filtered_bid_demand_calculation(), Filtered_bid_supply_calculation(), power_market_process_set(), and power_market_process_update().
International_Market_Optimization()
void power_market::International_Market_Optimization (int tick, market_inform & Market)
Definition at line 309 of file IMO.cpp.
References power_market::parameters::price_ID_bimap::bidded_price, power_market::market_inform::bidded_price_map, power_market::market_inform::confirmed, power_market::network_graph::confirmed_power, power_market::market_inform::cross_border_zone_start, power_market::results::demand, power_market::market_inform::demand_default, power_market::market_inform::merit_order_curve, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::network_graph::num_vertice, power_market::market_inform::num_zone, power_market::network_graph::power_constraint, power_market::results::price, power_market::market_inform::price_intervals, power_market::market_inform::Problem, power_market::results::ratio_demand, power_market::results::ratio_supply, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, and power_market::results::supply.
Referenced by power_market_process_set(), and power_market_process_update().
International_Market_Price_Estimation()
void power_market::International_Market_Price_Estimation (int tick, market_inform & International_Market, power_network::network_inform & Power_network_inform, configuration::process_config & process_par)
Definition at line 405 of file IMO.cpp.
Referenced by power_market_process_set(), and power_market_process_update().
International_Market_Set()
void power_market::International_Market_Set (market_inform & International_Market, power_network::network_inform & Power_network_inform, int Time, fin_market fin_market)
Definition at line 59 of file IMO.cpp.
References power_market::parameters::price_ID_bimap::bidded_price, power_market::parameters::bidded_price(), power_market::market_inform::bidded_price_map, power_network::points_struct::bidding_zone, power_network::cbt_struct::bz_names, power_market::fin_market::cbt, power_network::network_inform::cbt, power_market::market_inform::confirmed, power_market::network_graph::confirmed_power, power_market::market_inform::cross_border_zone_start, power_market::results::demand, power_market::fin_market::demand, power_market::market_inform::demand_default, power_network::cbt_struct::flow_constraint, basic::get_file_dim(), power_market::network_graph::incidence, power_market::network_graph::line_capacity_matrix, Market_Initialization(), power_market::market_inform::merit_order_curve, power_market::fin_market::moc, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::network_graph::num_vertice, power_market::market_inform::num_zone, Operation_Initialization(), power_network::network_inform::points, power_market::network_graph::power_constraint, power_market::results::price, power_market::settlement::price_demand, power_market::market_inform::price_intervals, power_market::settlement::price_supply, power_market::market_inform::Problem, power_market::results::ratio_demand, power_market::results::ratio_supply, basic::read_file(), power_market::market_inform::redispatch, power_market::fin_market::solar, power_market::results::supply, power_market::market_inform::time_intervals, power_market::fin_market::wind_off, power_market::fin_market::wind_on, and power_market::market_inform::zone_names.
Referenced by default_demand_set().
Market_Initialization()
void power_market::Market_Initialization (market_inform & Market)
Definition at line 28 of file power_market_func.cpp.
References power_market::market_inform::actual, power_market::market_inform::confirmed, power_market::market_inform::num_zone, power_market::market_inform::price_intervals, power_market::results::ratio_demand, power_market::results::ratio_supply, power_market::market_inform::reference_price, power_market::market_inform::submitted_demand, and power_market::market_inform::submitted_supply.
Referenced by Balancing_bid_calculation(), Confirmed_bid_calculation(), DSO_Markets_Set(), Filtered_bid_demand_calculation(), Filtered_bid_supply_calculation(), International_Market_Set(), Submitted_bid_calculation(), and TSO_Market_Set().
Markets_results_print()
void power_market::Markets_results_print (market_whole_inform & Power_market_inform, configuration::process_config & process_par)
Definition at line 149 of file power_market_output.cpp.
References power_market::market_whole_inform::International_Market, local::Market_results_print(), and power_market::market_whole_inform::TSO_Market.
Referenced by main().
Operation_Initialization()
void power_market::Operation_Initialization (market_inform & Market, int Time)
Definition at line 40 of file power_market_func.cpp.
References power_market::schedule::balancing, power_market::schedules::cross_border, power_market::schedules::end_user, power_market::schedule::EOM, power_market::schedules::hydro, power_market::schedules::industrial, power_market::market_inform::num_zone, power_market::market_inform::operation, power_market::schedules::pump_storage, power_market::schedule::redispatch, power_market::schedules::slack, and power_market::schedules::wind.
Referenced by International_Market_Set().
power_market_process_set()
void power_market::power_market_process_set (power_network::network_inform & Power_network_inform, market_whole_inform & Power_market_inform, configuration::process_config & process_par)
Definition at line 22 of file power_market_proc.cpp.
References agent::agents_balancing_update(), agent::agents_filter_demand_update(), agent::agents_filter_supply_update(), agent::agents_redispatch_update(), agent::agents_set(), agent::agents_status_update(), Balancing_bid_calculation(), Confirmed_bid_calculation(), configuration::process_config::control_reserve_flag, spatial_field::fin_field::demand, spatial_field::fin_field::dir, power_network::network_inform::DSO_cluster, configuration::process_config::DSO_filter_flag, power_market::market_whole_inform::DSO_Markets, DSO_Markets_Set(), Filtered_bid_demand_calculation(), Filtered_bid_supply_calculation(), Flow_Based_Market_LP_Set(), Flow_Based_Market_Optimization(), power_network::HELM_Node_Update(), power_network::HELM_Set(), power_network::HELM_Solve(), spatial_field::fin_field::imbalance, power_market::market_whole_inform::International_Market, International_Market_Optimization(), International_Market_Price_Estimation(), Simplified_network_print(), spatial_field::fin_field::solar, spatial_field::spatial_field_store(), Submitted_bid_calculation(), configuration::process_config::time_boundary, configuration::process_config::total_time, power_market::market_whole_inform::TSO_Market, TSO_Market_Actual_Results_Get(), TSO_Market_Scheduled_Results_Get(), TSO_Market_Set(), and spatial_field::fin_field::wind_on.
Referenced by main().
power_market_process_update()
void power_market::power_market_process_update (power_network::network_inform & Power_network_inform, market_whole_inform & Power_market_inform, configuration::process_config & process_par)
Definition at line 93 of file power_market_proc.cpp.
References agent::agents_balancing_update(), agent::agents_filter_demand_update(), agent::agents_filter_supply_update(), agent::agents_redispatch_update(), agent::agents_status_update(), agent::agents_submit_update(), Balancing_bid_calculation(), Confirmed_bid_calculation(), configuration::process_config::control_reserve_flag, configuration::process_config::DSO_filter_flag, Filtered_bid_demand_calculation(), Filtered_bid_supply_calculation(), Flow_Based_Market_Optimization(), power_network::HELM_Node_Update(), power_network::HELM_Solve(), power_market::market_whole_inform::International_Market, International_Market_Optimization(), International_Market_Price_Estimation(), Submitted_bid_calculation(), configuration::process_config::time_boundary, configuration::process_config::total_time, power_market::market_whole_inform::TSO_Market, TSO_Market_Actual_Results_Get(), and TSO_Market_Scheduled_Results_Get().
Referenced by main().
Simplified_network_print()
void power_market::Simplified_network_print (market_whole_inform & Power_market_inform)
Definition at line 159 of file power_market_output.cpp.
References local::Simplified_network_print(), and power_market::market_whole_inform::TSO_Market.
Referenced by power_market_process_set().
Submitted_bid_calculation()
void power_market::Submitted_bid_calculation (market_whole_inform & Power_market_inform, power_network::network_inform & Power_network_inform)
Definition at line 239 of file IMO.cpp.
References power_market::market_whole_inform::agent_profiles, power_network::points_struct::bidding_zone, power_market::agent_profiles_struct::end_users, agent::industrial::profiles::HV, agent::power_supplier::storage::HV, agent::power_supplier::plants::HV_plant, agent::power_supplier::profiles::hydro, power_market::agent_profiles_struct::industrial, power_market::market_whole_inform::International_Market, agent::power_supplier::storage::LV, agent::power_supplier::plants::LV_plant, Market_Initialization(), power_network::network_inform::points, power_market::agent_profiles_struct::power_supplier, agent::power_supplier::profiles::pump_storage, agent::power_supplier::profiles::slack, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, and agent::power_supplier::profiles::wind.
Referenced by power_market_process_set(), and power_market_process_update().
TSO_Market_Actual_Results_Get()
void power_market::TSO_Market_Actual_Results_Get (int tick, market_inform & Market)
Definition at line 384 of file TSO.cpp.
References power_market::market_inform::actual, power_market::network_graph::actual_power, power_market::parameters::price_ID_bimap::bidded_price, power_market::market_inform::bidded_price_map, power_market::results::demand, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::network_graph::num_vertice, power_market::results::price, power_market::market_inform::price_intervals, power_market::market_inform::Problem, power_market::results::ratio_demand, power_market::results::ratio_supply, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, and power_market::results::supply.
Referenced by power_market_process_set(), and power_market_process_update().
TSO_Market_Scheduled_Results_Get()
void power_market::TSO_Market_Scheduled_Results_Get (int tick, market_inform & Market)
Definition at line 215 of file TSO.cpp.
References power_market::parameters::price_ID_bimap::bidded_price, power_market::market_inform::bidded_price_map, power_market::market_inform::confirmed, power_market::network_graph::confirmed_power, power_market::results::demand, power_market::market_inform::network, power_market::network_graph::num_edges, power_market::network_graph::num_vertice, power_market::results::price, power_market::market_inform::price_intervals, power_market::market_inform::Problem, power_market::results::ratio_demand, power_market::results::ratio_supply, power_market::market_inform::submitted_demand, power_market::market_inform::submitted_supply, and power_market::results::supply.
Referenced by power_market_process_set(), and power_market_process_update().
TSO_Market_Set()
void power_market::TSO_Market_Set (market_inform & TSO_Market, power_network::network_inform & Power_network_inform, int Time)
Definition at line 6 of file TSO.cpp.
References power_market::market_inform::actual, power_market::network_graph::actual_power, power_market::network_graph::admittance, power_market::market_inform::balancing, power_market::parameters::bidded_price(), power_market::market_inform::bidded_price_map, power_network::nodes_struct::bidding_zone, power_market::market_inform::confirmed, power_market::network_graph::confirmed_power, power_market::settlement::cost, power_market::results::demand, power_market::settlement::demand_down, power_market::settlement::demand_up, power_network::edges_struct::distance, power_network::network_inform::edges, power_market::market_inform::EOM, power_network::edges_struct::from, power_market::market_inform::imbalance, power_network::technical_parameters::impedenace_base_levels, power_market::network_graph::incidence, Market_Initialization(), power_market::market_inform::network, power_network::network_inform::nodes, power_market::network_graph::num_edges, power_market::network_graph::num_vertice, power_market::market_inform::num_zone, power_market::network_graph::power_constraint, power_network::technical_parameters::power_limit, power_market::results::price, power_market::settlement::price_demand, power_market::settlement::price_down, power_market::settlement::price_supply, power_market::settlement::price_up, power_market::market_inform::redispatch, power_network::technical_parameters::s_base, power_market::results::supply, power_market::settlement::supply_down, power_market::settlement::supply_up, power_network::network_inform::tech_parameters, power_network::technical_parameters::theta_trans_limit, power_market::market_inform::time_intervals, power_network::edges_struct::to, power_market::settlement::utility, power_network::edges_struct::voltage_base, power_market::network_graph::voltage_constraint, power_network::technical_parameters::z_trans_series, and power_market::market_inform::zone_names.
Referenced by power_market_process_set().