trEnD: basic Namespace Reference
basic Namespace Reference
Functions
std::vector< std::string > get_col_name (std::string, int)
std::vector< int > get_file_dim (std::string)
Eigen::MatrixXd read_file (int, int, std::string)
void write_file (Eigen::MatrixXd, std::string, std::vector< std::string >)
Function Documentation
get_col_name()
std::vector< std::string > basic::get_col_name (std::string filename, int col_num)
Definition at line 4 of file rw_csv.cpp.
get_file_dim()
std::vector< int > basic::get_file_dim (std::string filename)
Definition at line 26 of file rw_csv.cpp.
Referenced by power_network::power_network_input_process(), and power_market::Submitted_bid_calculation().
read_file()
Eigen::MatrixXd basic::read_file (int num_row, int num_col, std::string filename)
Definition at line 60 of file rw_csv.cpp.
Referenced by power_market::International_Market_Set(), main(), power_network::power_network_input_process(), and power_market::Submitted_bid_calculation().
write_file()
void basic::write_file (Eigen::MatrixXd data, std::string filename, std::vector< std::string > col_name)
Definition at line 89 of file rw_csv.cpp.
Referenced by power_market::International_Market_Output(), and main().