trEnD: power_network::technical_parameters Struct Reference
power_network::technical_parameters Struct Reference
Technical parameters of the power network.
#include <power_network.h>
Public Attributes
voltage and power boundaries of the power network
int phase_num = 3
int voltage_cutoff_trans = 132
int voltage_cutoff_conn = 66
int voltage_cutoff_distr = 33
double power_limit_trans = .75
double power_limit_conn = .25
double power_limit_distr = .1
statistical parameters of power network
int line_trans = 2
double line_density_conn = 2
int line_num_distr = 122782 * 1.
double line_density_distr
double fraction_dim_distr = 1.5
physical parameters of power lines
std::complex< double > z_trans_series = std::complex<double> (2.5 * pow(10., -5.) / line_trans, 2.5 * pow(10., -4.) / line_trans)
std::complex< double > y_trans_shunt = std::complex<double> (0., 2 * pow(10., -9.) * line_trans)
std::complex< double > z_conn_series = std::complex<double> (1.2 * pow(10., -4.), 4. * pow(10., -4.))
std::complex< double > y_conn_shunt = std::complex<double> (0., 4.5 * pow(10., -10.))
std::complex< double > z_distr_series = std::complex<double> (6. * pow(10., -4.), 6. * pow(10., -4.))
std::complex< double > y_distr_shunt = std::complex<double> (0., 1. * pow(10., -10.))
double theta_trans_limit = boost::math::constants::pi<double>() / 180.
double theta_distr_limit = theta_trans_limit / 2.
std::map< int, double > power_limit
non-dimensionalization parameters
double s_base = 1.
std::map< int, int > voltage_base_levels
std::map< int, double > impedenace_base_levels
void set_level_maps (edges &edges)
double z_base_conn ()
double z_base_distr ()
Detailed Description
Technical parameters of the power network.
Including:
cutoff voltage level of the transmission and distribution network
number and density of power lines of the distribution network
fractional dimension of the power lines of the distribution network
series and shunt impedance of the power lines
Definition at line 234 of file power_network.h.
Member Function Documentation
set_level_maps()
void power_network::technical_parameters::set_level_maps (edges & edges) inline
Definition at line 308 of file power_network.h.
References power_network::edges::voltage_base.
Referenced by power_network::power_network_input_process().
z_base_conn()
double power_network::technical_parameters::z_base_conn () inline
Definition at line 332 of file power_network.h.
References s_base.
Referenced by power_network::HELM_Set().
z_base_distr()
double power_network::technical_parameters::z_base_distr () inline
Definition at line 336 of file power_network.h.
References s_base.
Referenced by power_network::HELM_Set().
Member Data Documentation
fraction_dim_distr
double power_network::technical_parameters::fraction_dim_distr = 1.5
Fractional dimension of the distribution network.
Definition at line 268 of file power_network.h.
Referenced by power_network::HELM_Set().
impedenace_base_levels
std::map<int, double> power_network::technical_parameters::impedenace_base_levels
Hash table (mapping) of per phase base impedance levels in Ohm.
Definition at line 304 of file power_network.h.
Referenced by power_network::HELM_Set(), and power_network::HELM_Transmission_Set().
line_density_conn
double power_network::technical_parameters::line_density_conn = 2
Density of power lines per point connecting distribution and transmission power network.
Definition at line 262 of file power_network.h.
Referenced by power_network::HELM_Set().
line_density_distr
double power_network::technical_parameters::line_density_distr
Density of power lines per point in the distribution network.
Definition at line 266 of file power_network.h.
Referenced by power_network::HELM_Set(), and power_network::network_inform::set_line_density().
line_num_distr
int power_network::technical_parameters::line_num_distr = 122782 * 1.
Total number of power lines in the distribution network.
Definition at line 264 of file power_network.h.
Referenced by power_network::network_inform::set_line_density().
line_trans
int power_network::technical_parameters::line_trans = 2
Number of lines a transmission edge possesses.
Definition at line 260 of file power_network.h.
phase_num
int power_network::technical_parameters::phase_num = 3
Number of phases at a power lines.
Definition at line 240 of file power_network.h.
power_limit
std::map<int, double> power_network::technical_parameters::power_limit
Hash table (mapping) of per phase power flow limits on an edge at different voltage base levels, in MW.
Definition at line 292 of file power_network.h.
power_limit_conn
double power_network::technical_parameters::power_limit_conn = .25
Power carrying capacity per voltage (MW / kV) of HV distribution lines.
Definition at line 250 of file power_network.h.
power_limit_distr
double power_network::technical_parameters::power_limit_distr = .1
Power carrying capacity per voltage (MW / kV) of LV distribution lines.
Definition at line 252 of file power_network.h.
power_limit_trans
double power_network::technical_parameters::power_limit_trans = .75
Power carrying capacity per voltage (MW / kV) of transmission lines.
Definition at line 248 of file power_network.h.
s_base
double power_network::technical_parameters::s_base = 1.
Reference value of power on the line (in MW, per phase) for non-dimensionalization into p.u..
Definition at line 300 of file power_network.h.
Referenced by z_base_conn(), and z_base_distr().
theta_distr_limit
double power_network::technical_parameters::theta_distr_limit = theta_trans_limit / 2.
Phase angle limits on a distribution node.
Definition at line 290 of file power_network.h.
theta_trans_limit
double power_network::technical_parameters::theta_trans_limit = boost::math::constants::pi<double>() / 180.
Phase angle limits on a transmission node.
Definition at line 288 of file power_network.h.
voltage_base_levels
std::map<int, int> power_network::technical_parameters::voltage_base_levels
Hash table (mapping) of line to line base voltage levels in kV.
Definition at line 302 of file power_network.h.
voltage_cutoff_conn
int power_network::technical_parameters::voltage_cutoff_conn = 66
Voltage level of connection between the transmission and the distribution network.
Definition at line 244 of file power_network.h.
voltage_cutoff_distr
int power_network::technical_parameters::voltage_cutoff_distr = 33
Cutoff voltage level of the distribution network.
Definition at line 246 of file power_network.h.
voltage_cutoff_trans
int power_network::technical_parameters::voltage_cutoff_trans = 132
Cutoff voltage level of the transmission network.
Definition at line 242 of file power_network.h.
y_conn_shunt
std::complex<double> power_network::technical_parameters::y_conn_shunt = std::complex<double> (0., 4.5 * pow(10., -10.))
Shunt admittance (ohm^(-1) per meter) of HV distribution line.
Definition at line 282 of file power_network.h.
Referenced by power_network::HELM_Set().
y_distr_shunt
std::complex<double> power_network::technical_parameters::y_distr_shunt = std::complex<double> (0., 1. * pow(10., -10.))
Shunt admittance (ohm^(-1) per meter) of MV distribution line.
Definition at line 286 of file power_network.h.
Referenced by power_network::HELM_Set().
y_trans_shunt
std::complex<double> power_network::technical_parameters::y_trans_shunt = std::complex<double> (0., 2 * pow(10., -9.) * line_trans)
Shunt admittance (ohm^(-1) per meter) of transmission line.
Definition at line 278 of file power_network.h.
Referenced by power_network::HELM_Set(), and power_network::HELM_Transmission_Set().
z_conn_series
std::complex<double> power_network::technical_parameters::z_conn_series = std::complex<double> (1.2 * pow(10., -4.), 4. * pow(10., -4.))
Series impedance (ohm per meter) of HV distribution line.
Definition at line 280 of file power_network.h.
Referenced by power_network::HELM_Set().
z_distr_series
std::complex<double> power_network::technical_parameters::z_distr_series = std::complex<double> (6. * pow(10., -4.), 6. * pow(10., -4.))
Series impedance (ohm per meter) of MV distribution line.
Definition at line 284 of file power_network.h.
Referenced by power_network::HELM_Set().
z_trans_series
std::complex<double> power_network::technical_parameters::z_trans_series = std::complex<double> (2.5 * pow(10., -5.) / line_trans, 2.5 * pow(10., -4.) / line_trans)
Series impedance (ohm per meter) of transmission line.
Definition at line 276 of file power_network.h.
Referenced by power_network::HELM_Set(), and power_network::HELM_Transmission_Set().
The documentation for this struct was generated from the following file:
power_network.h