trEnD: LP_gpa_fast.cpp File Reference
LP_gpa_fast.cpp File Reference
#include "../basic/LP_gpa.h"
Functions
void LP_boundary_ie_reduced_generation (LP_object &Problem)
void LP_boundary_ie_reduced_normalization (LP_object &Problem)
void LP_constraint_eq_redundant_deletion (LP_object &Problem)
void LP_constraint_ie_reduced_cov_matrix_generation (LP_object &Problem)
void LP_constraint_ie_reduced_generation (LP_object &Problem)
void LP_constraint_ie_reduced_normalization (LP_object &Problem)
void LP_constraint_redundant_matrix_solver (LP_object &Problem)
void LP_feasible_solution_reduced_generation (LP_object &Problem)
void LP_objective_ie_reduced_cov_matrix_generation (LP_object &Problem)
void LP_objective_reduced_generation (LP_object &Problem)
void LP_optimization (LP_object &Problem, bool stepwise_obj)
void LP_process (LP_object &Problem, std::string Problem_name, bool result_output, bool find_sol, bool stepwise_obj, bool constraint_update, bool boundary_update, bool objective_update)
void LP_result_print (LP_object &Problem, std::string Problem_name="Linear Problem")
void LP_solution_permutation (LP_object &Problem, bool inverse)
void LP_variables_permutation (LP_object &Problem, bool stepwise_obj)
Function Documentation
LP_boundary_ie_reduced_generation()
void LP_boundary_ie_reduced_generation (LP_object & Problem)
Definition at line 133 of file LP_gpa_fast.cpp.
References LP_object::Boundary, LP_object::Constraints_eq_num, LP_object::Constraints_ie_num, LP_boundary::eq_vector, LP_boundary::ie_orig_matrix, LP_boundary::ie_reduced_matrix, LP_matrix_solver::lu, LP_object::Solver, and LP_object::Variables_num.
Referenced by LP_process().
LP_boundary_ie_reduced_normalization()
void LP_boundary_ie_reduced_normalization (LP_object & Problem)
Definition at line 191 of file LP_gpa_fast.cpp.
References LP_object::Boundary, LP_object::Constraint, LP_object::Constraints_eq_num, LP_constraint::ie_reduced_matrix, LP_boundary::ie_reduced_matrix, LP_constraint::norm, and LP_object::Variables_num.
Referenced by LP_process().
LP_constraint_eq_redundant_deletion()
void LP_constraint_eq_redundant_deletion (LP_object & Problem)
Definition at line 7 of file LP_gpa_fast.cpp.
References LP_object::Boundary, LP_object::Constraint, LP_object::Constraints_eq_num, LP_constraint::eq_orig_matrix, LP_boundary::eq_vector, LP_matrix_solver::qr, and LP_object::Solver.
Referenced by LP_process().
LP_constraint_ie_reduced_cov_matrix_generation()
void LP_constraint_ie_reduced_cov_matrix_generation (LP_object & Problem)
Definition at line 202 of file LP_gpa_fast.cpp.
References LP_object::Constraint, LP_constraint::ie_reduced_cov_matrix, and LP_constraint::ie_reduced_matrix.
Referenced by LP_process().
LP_constraint_ie_reduced_generation()
void LP_constraint_ie_reduced_generation (LP_object & Problem)
Definition at line 102 of file LP_gpa_fast.cpp.
References LP_object::Constraint, LP_object::Constraints_eq_num, LP_object::Constraints_ie_num, LP_constraint::eq_orig_matrix, LP_constraint::ie_orig_matrix, LP_constraint::ie_reduced_matrix, LP_matrix_solver::lu, LP_object::Solver, and LP_object::Variables_num.
Referenced by LP_process().
LP_constraint_ie_reduced_normalization()
void LP_constraint_ie_reduced_normalization (LP_object & Problem)
Definition at line 177 of file LP_gpa_fast.cpp.
References LP_object::Constraint, LP_object::Constraints_eq_num, LP_object::Constraints_ie_num, LP_constraint::ie_reduced_matrix, LP_constraint::norm, and LP_object::Variables_num.
Referenced by LP_process().
LP_constraint_redundant_matrix_solver()
void LP_constraint_redundant_matrix_solver (LP_object & Problem)
Definition at line 98 of file LP_gpa_fast.cpp.
References LP_object::Constraint, LP_object::Constraints_eq_num, LP_constraint::eq_orig_matrix, LP_matrix_solver::lu, and LP_object::Solver.
Referenced by LP_process().
LP_feasible_solution_reduced_generation()
void LP_feasible_solution_reduced_generation (LP_object & Problem)
Definition at line 172 of file LP_gpa_fast.cpp.
References LP_object::Constraints_eq_num, LP_solution::orig_vector, LP_solution::reduced_vector, LP_object::Solution, and LP_object::Variables_num.
Referenced by LP_process().
LP_objective_ie_reduced_cov_matrix_generation()
void LP_objective_ie_reduced_cov_matrix_generation (LP_object & Problem)
Definition at line 207 of file LP_gpa_fast.cpp.
References LP_object::Constraint, LP_objective::ie_reduced_cov_vector, LP_constraint::ie_reduced_matrix, LP_object::Objective, and LP_objective::reduced_vector.
Referenced by LP_process().
LP_objective_reduced_generation()
void LP_objective_reduced_generation (LP_object & Problem)
Definition at line 157 of file LP_gpa_fast.cpp.
References LP_object::Constraint, LP_object::Constraints_eq_num, LP_constraint::eq_orig_matrix, LP_matrix_solver::lu, LP_object::Objective, LP_objective::orig_vector, LP_objective::reduced_vector, LP_object::Solver, and LP_object::Variables_num.
Referenced by LP_process().
LP_optimization()
void LP_optimization (LP_object & Problem, bool stepwise_obj)
Definition at line 212 of file LP_gpa_fast.cpp.
References LP_object::Boundary, LP_object::Constraint, LP_object::Constraints_eq_num, LP_object::Constraints_ie_num, LP_constraint::eq_orig_matrix, LP_boundary::eq_vector, LP_constraint::ie_reduced_cov_matrix, LP_objective::ie_reduced_cov_vector, LP_constraint::ie_reduced_matrix, LP_boundary::ie_reduced_matrix, LP_matrix_solver::ldlt, LP_matrix_solver::lu, LP_object::Objective, LP_objective::orig_value, LP_objective::orig_vector, LP_solution::orig_vector, LP_constraint::permutation_matrix, LP_matrix_solver::qr, LP_objective::reduced_value, LP_objective::reduced_vector, LP_solution::reduced_vector, LP_object::Solution, LP_object::Solver, LP_objective::update_coeff, LP_object::Variables_num, and LP_objective::varying_vector.
Referenced by LP_process().
LP_process()
void LP_process (LP_object & Problem, std::string Problem_name, bool result_output, bool find_sol, bool stepwise_obj, bool constraint_update, bool boundary_update, bool objective_update)
Definition at line 512 of file LP_gpa_fast.cpp.
References LP_boundary_ie_reduced_generation(), LP_boundary_ie_reduced_normalization(), LP_constraint_eq_redundant_deletion(), LP_constraint_ie_reduced_cov_matrix_generation(), LP_constraint_ie_reduced_generation(), LP_constraint_ie_reduced_normalization(), LP_constraint_redundant_matrix_solver(), LP_feasible_solution_reduced_generation(), LP_objective_ie_reduced_cov_matrix_generation(), LP_objective_reduced_generation(), LP_optimization(), LP_result_print(), LP_solution_permutation(), and LP_variables_permutation().
Referenced by storage_schedule_LP().
LP_result_print()
void LP_result_print (LP_object & Problem, std::string Problem_name = "Linear Problem")
Definition at line 495 of file LP_gpa_fast.cpp.
References LP_object::Objective, LP_objective::orig_value, LP_solution::orig_vector, LP_objective::reduced_value, LP_solution::reduced_vector, and LP_object::Solution.
Referenced by LP_process().
LP_solution_permutation()
void LP_solution_permutation (LP_object & Problem, bool inverse)
Definition at line 88 of file LP_gpa_fast.cpp.
References LP_object::Constraint, LP_solution::orig_vector, LP_constraint::permutation_matrix, and LP_object::Solution.
Referenced by LP_process().
LP_variables_permutation()
void LP_variables_permutation (LP_object & Problem, bool stepwise_obj)
Definition at line 25 of file LP_gpa_fast.cpp.
References LP_object::Boundary, LP_object::Constraint, LP_object::Constraints_eq_num, LP_constraint::eq_orig_matrix, LP_boundary::ie_orig_matrix, LP_object::Objective, LP_objective::orig_vector, LP_constraint::permutation_matrix, LP_matrix_solver::qr, LP_object::Solver, LP_object::Variables_num, and LP_objective::varying_vector.
Referenced by LP_process().